#!/usr/bin/env python3
"""Lift the generated local-projection bake into a plain host header.

The bake ships as six GBDK bank translation units whose payload is only two
arrays each. Rung 2 needs to evaluate that field on the host, so this extracts
the bytes verbatim rather than reimplementing the generator: whatever the ROM
was built from is what gets tested.
"""
import re, sys
from pathlib import Path

src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("build/generated/polar_projection")
out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("tools/rung1/proj_tables.h")

def arr(text, name):
    m = re.search(name + r"\[(\d+)\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m: sys.exit(f"{name} not found")
    vals = [int(v) for v in m.group(2).replace("\n", " ").split(",") if v.strip()]
    if len(vals) != int(m.group(1)): sys.exit(f"{name}: {len(vals)} != {m.group(1)}")
    return vals

banks = []
for b in range(6):
    t = (src / f"tilesector_polar_proj_bank{b}.c").read_text()
    banks.append((arr(t, "k_proj_off"), arr(t, "k_proj_data")))

noff = len(banks[0][0])
maxdata = max(len(d) for _, d in banks)
L = [f"/* GENERATED by tools/rung1/make_proj_tables.py from {src}. Do not edit. */",
     "#ifndef RUNG1_PROJ_TABLES_H", "#define RUNG1_PROJ_TABLES_H", "#include <stdint.h>",
     f"#define PROJ_BANKS 6", f"#define PROJ_OFF_N {noff}", f"#define PROJ_DATA_MAX {maxdata}",
     f"static const uint16_t k_proj_off_b[PROJ_BANKS][PROJ_OFF_N] = {{"]
for off, _ in banks:
    L.append("  {" + ",".join(str(v) for v in off) + "},")
L.append("};")
L.append(f"static const uint16_t k_proj_data_len[PROJ_BANKS] = {{" +
         ",".join(str(len(d)) for _, d in banks) + "};")
L.append(f"static const uint8_t k_proj_data_b[PROJ_BANKS][PROJ_DATA_MAX] = {{")
for _, d in banks:
    body = ",".join(str(v) for v in d)
    L.append("  {" + body + "},")
L.append("};")
L.append("#endif")
out.write_text("\n".join(L) + "\n")
print(f"wrote {out}: {noff-1} cells/bank, data {[len(d) for _,d in banks]} bytes")
