#!/usr/bin/env python3
"""Apply the experimental zero-new-pattern floor-light runtime integration.

This deliberately patches only the CI/worktree used for the runtime probe. The
branch's known-good Polar renderer remains a clean baseline while the workflow
can build baseline and lit ROMs from the same commit and cycle-profile the delta.

The lighting kernel is compiled as a separate BANKED translation unit. This is
important: the mature Polar renderer object is already close to a 16 KiB bank,
so including the lighting kernel in tilesector_polar_renderer.c makes BankPack
reject the object even though the overall 8-bank ROM still has room.
"""
from pathlib import Path
import re


def replace_once(text: str, old: str, new: str, label: str) -> str:
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"{label}: expected exactly one anchor, found {n}")
    return text.replace(old, new, 1)


def extract_generated_array(name: str, renamed: str) -> str:
    parts = []
    for p in sorted(Path("src/generated").glob("tilesector_polar_data_part*.inc")):
        parts.append(p.read_text())
    data = "\n".join(parts)
    pat = re.compile(
        r"static\s+const\s+[^;{]+?\b" + re.escape(name) +
        r"\s*\[[^\]]*\]\s*=\s*\{.*?\};",
        re.S,
    )
    m = pat.search(data)
    if not m:
        raise SystemExit(f"generated array not found: {name}")
    return m.group(0).replace(name, renamed, 1)


# ---------------------------------------------------------------------------
# 1) Keep the renderer small: only add a BANKED prototype and one call/frame.
# ---------------------------------------------------------------------------
renderer = Path("src/tilesector_polar_renderer.c")
s = renderer.read_text()

proto_anchor = "\nvoid tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {"
proto_repl = (
    "\n#ifdef __SDCC\n"
    "void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED;\n"
    "#endif\n\n"
    "void tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {"
)
s = replace_once(s, proto_anchor, proto_repl, "renderer light prototype")

call_anchor = "    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\ndone:"
call_repl = "    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\n#ifdef __SDCC\n    if(g_tspf_appearance_mode==0u)tsp_polar_floor_light(s,out_map);\n#endif\ndone:"
s = replace_once(s, call_anchor, call_repl, "renderer light call")
renderer.write_text(s)


# ---------------------------------------------------------------------------
# 2) Generate a self-contained, separately bankable lighting translation unit.
#    Reuse the exact tiny projection LUTs from the generated Polar field, but
#    copy only the three arrays the light pass needs (~1 KiB), not the whole
#    generated topology/recipe corpus.
# ---------------------------------------------------------------------------
inc = Path("src/tilesector_polar_floor_light.inc").read_text()
fn_old = "static void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]){"
fn_new = "void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED {"
inc = replace_once(inc, fn_old, fn_new, "floor-light exported BANKED entry")

sin_lut = extract_generated_array("k_tspf_sin_q7", "k_fl_sin_q7")
recip_lut = extract_generated_array("k_tspf_recip8_q16", "k_fl_recip8_q16")
invz_lut = extract_generated_array("k_tspf_invz", "k_fl_invz")

runtime_src = f'''/* GENERATED by tools/apply_lattice_floor_light_runtime.py.
 * Experimental free-camera floor lighting: one BANKED call per rendered update.
 * No new VRAM patterns; this object is intentionally separate from the mature
 * Polar renderer so BankPack can place it in its own 16 KiB ROM bank. */
#include <stdint.h>
#if defined(__SDCC)
#include <gbdk/platform.h>
#endif
#include "tilesector_polar.h"

#if defined(__SDCC)
extern uint8_t g_polar_nt_cov_cur[60];
extern uint8_t g_polar_nt_row_min[18];
extern uint8_t g_polar_nt_row_max[18];

static const uint16_t k_fl_row_base[TSP_ROWS] = {{
    0u,20u,40u,60u,80u,100u,120u,140u,160u,
    180u,200u,220u,240u,260u,280u,300u,320u,340u
}};
static const uint8_t k_fl_nt_mask8[8] = {{1u,2u,4u,8u,16u,32u,64u,128u}};

{sin_lut}
{recip_lut}
{invz_lut}

static int8_t flrt_clamp_s8(int16_t v,int8_t lo,int8_t hi){{if(v<lo)return lo;if(v>hi)return hi;return (int8_t)v;}}
static int16_t flrt_shr_signed(int16_t v,uint8_t n){{return v>=0?(int16_t)(v>>n):(int16_t)-(((-v)>>n));}}
static int8_t flrt_row_floor(int16_t y){{return y>=0?(int8_t)(y>>3):(int8_t)-(((-y)+7)>>3);}}

static uint8_t flrt_ratio_q8_exact(uint8_t n,uint8_t d){{
    uint16_t rec,p_lo,p_hi,q;
    if(!d)return 0u;
    rec=k_fl_recip8_q16[d];
    p_lo=(uint16_t)n*(uint8_t)rec;
    p_hi=(uint16_t)n*(uint8_t)(rec>>8);
    q=(uint16_t)(p_hi+((p_lo+128u)>>8));
    return (uint8_t)q;
}}

static uint8_t flrt_inv_for_dq4(int16_t dq4){{
    uint16_t a=(uint16_t)(dq4<0?-dq4:dq4);uint8_t z,f,x0,x1;int16_t d;
    if(a<=(10u<<4))return 255u;
    if(a>=(127u<<4))return k_fl_invz[127];
    z=(uint8_t)(a>>4);f=(uint8_t)(a&15u);x0=k_fl_invz[z];x1=k_fl_invz[(uint8_t)(z+1u)];d=(int16_t)x1-(int16_t)x0;
    return (uint8_t)((int16_t)x0+flrt_shr_signed((int16_t)(d*(int16_t)f+(d>=0?8:-8)),4));
}}

static void flrt_put_cell(uint16_t *out,uint8_t row,uint8_t col,uint16_t word){{
    uint16_t idx=k_fl_row_base[row]+col;
    uint8_t cov_i=(uint8_t)(col+col+col+(row>>3));
    g_polar_nt_cov_cur[cov_i]|=k_fl_nt_mask8[row&7u];
    if(out[idx]!=word){{
        out[idx]=word;
        if(g_polar_nt_row_min[row]==0xffu||col<g_polar_nt_row_min[row])g_polar_nt_row_min[row]=col;
        if(col>g_polar_nt_row_max[row])g_polar_nt_row_max[row]=col;
    }}
}}

#define clamp_s8 flrt_clamp_s8
#define shr_signed flrt_shr_signed
#define row_floor flrt_row_floor
#define ratio_q8_exact flrt_ratio_q8_exact
#define inv_for_dq4 flrt_inv_for_dq4
#define put_cell flrt_put_cell
#define k_tspf_sin_q7 k_fl_sin_q7
#define k_nt_mask8 k_fl_nt_mask8

{inc}

#undef clamp_s8
#undef shr_signed
#undef row_floor
#undef ratio_q8_exact
#undef inv_for_dq4
#undef put_cell
#undef k_tspf_sin_q7
#undef k_nt_mask8
#endif /* __SDCC */
'''
Path("src/tilesector_polar_floor_light_runtime.c").write_text(runtime_src)


# ---------------------------------------------------------------------------
# 3) Add exactly one independently bankable object to the lit build.
# ---------------------------------------------------------------------------
mk = Path("Makefile")
ms = mk.read_text()
obj_anchor = "POLAR_GG_OBJS := build/main_tilesector_polar_gg.o build/tilesector_polar_motion_gg.o build/tilesector_polar_renderer_gg.o build/tilesector_polar_ntstate_gg.o build/tilesector_polar_materialize_gg.o $(POLAR_NTUPLOAD_OBJ)"
obj_repl = obj_anchor + " build/tilesector_polar_floor_light_runtime_gg.o"
ms = replace_once(ms, obj_anchor, obj_repl, "Polar object list")
rule_anchor = "build/tilesector_polar_renderer_gg.o: src/tilesector_polar_renderer.c $(POLAR_PROJ_META) $(POLAR_DEPTHPLANE_HDR) | build\n\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n"
rule_repl = rule_anchor + "\nbuild/tilesector_polar_floor_light_runtime_gg.o: src/tilesector_polar_floor_light_runtime.c | build\n\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n"
ms = replace_once(ms, rule_anchor, rule_repl, "floor-light object rule")
mk.write_text(ms)


# ---------------------------------------------------------------------------
# 4) Palette/tile authoring remains the zero-new-pattern experiment.
# ---------------------------------------------------------------------------
main = Path("src/main_tilesector_polar_gg.c")
m = main.read_text()

pal_anchor = "    RGB(0,0,0),RGB(2,2,3),RGB(2,2,3),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
pal_repl = "    RGB(0,0,0),RGB(2,2,3),RGB(1,1,3),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
m = replace_once(m, pal_anchor, pal_repl, "palette-1 shadow slot")

edge_anchor = "static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
edge_repl = "static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c;if(shade==0u)c=(int8_t)y<line?C_OUT:C_FLOOR;else c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
m = replace_once(m, edge_anchor, edge_repl, "shade-zero floor edge authoring")

toggle_anchor = "    if(pressed&J_START){if(pad&J_B)g_tspf_appearance_mode=0u;else if(pad&J_A)g_tspf_appearance_mode=2u;else {++g_tspf_appearance_mode;if(g_tspf_appearance_mode>2u)g_tspf_appearance_mode=0u;}}"
toggle_repl = "    if(pressed&J_START)g_tspf_appearance_mode=0u;"
m = replace_once(m, toggle_anchor, toggle_repl, "appearance-mode pin")
main.write_text(m)

print("FLOOR_LIGHT_RUNTIME_PATCH=APPLIED")
print("LIGHT_TRANSLATION_UNIT=SEPARATE_BANKED_OBJECT")
print("BANKED_CALLS_PER_RENDERED_UPDATE=1")
print("LIGHT_POLYGONS=4")
print("INTERNAL_CAST_EDGES=4")
print("NEW_VRAM_PATTERNS=0")
print("SHADE0_EDGE_FAMILY=REPURPOSED_FOR_FLOOR_LIGHT")
print("PALETTE1_FLOOR=FULL_SHADOW_TILE")
