#!/usr/bin/env python3
"""Wire the compact receiver-owned Polar cast-plane bake into the GG runtime.

This replaces the old runtime shadow-polygon experiment with the intended Polar
shape: four static cast planes, treated as virtual wall-bottom edges.  The Z80
never constructs, clips, or scan-fills world polygons here.

For the two-room validation scene the receiver ownership gate is especially
cheap: Room A light is only valid beyond the x=80 portal plane, Room B beyond
x=112.  Those two gate planes are existing authored surface bounds.  The
runtime therefore intersects three cheap half-planes per receiver:
  Room A: cast from v2, cast from v3, x<=80 receiver gate
  Room B: cast from v6, cast from v7, x>=112 receiver gate

Each plane has a screen inverse-depth recurrence exactly like an arbitrary
straight Polar wall.  The two cast normal/yaw terms are PC-baked; the two
cardinal receiver gates get equally baked 256-entry terms in this patch.

The lighting translation unit is separately BANKED.  It writes only the
20x18 authoritative WRAM name-table shadow, marks existing coverage/dirty
state, and lets the mature VBlank uploader perform the actual VDP writes.
"""
from pathlib import Path
import re

BRANCH_NOTE = "POLAR_CAST_RUN_RUNTIME_PATCH=APPLIED"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"{label}: expected exactly one anchor, found {n}")
    return text.replace(old, new, 1)


def generated_c_array(name: str, renamed: str) -> str:
    data = "\n".join(p.read_text() for p in sorted(Path("src/generated").glob("tilesector_polar_data_part*.inc")))
    pat = re.compile(r"static\s+const\s+[^;{]+?\b" + re.escape(name) + r"\s*\[[^\]]*\]\s*=\s*\{.*?\};", re.S)
    m = pat.search(data)
    if not m:
        raise SystemExit(f"generated array not found: {name}")
    return m.group(0).replace(name, renamed, 1)


def generated_int_array(name: str):
    data = "\n".join(p.read_text() for p in sorted(Path("src/generated").glob("tilesector_polar_data_part*.inc")))
    m = re.search(r"\b" + re.escape(name) + r"\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", data, re.S)
    if not m:
        raise SystemExit(f"generated integer array not found: {name}")
    return [int(x) for x in re.findall(r"-?\d+", m.group(1))]


def c_i8(name: str, vals, cols=16) -> str:
    out=[f"static const int8_t {name}[{len(vals)}] = {{"]
    for i in range(0,len(vals),cols): out.append("    "+", ".join(str(int(v)) for v in vals[i:i+cols])+",")
    out.append("};")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Mature renderer: one banked call after opaque geometry, before lifetime
# reconciliation. Lighting therefore cannot overwrite a wall cell already
# claimed by the near-to-far geometry materializer.
# ---------------------------------------------------------------------------
renderer=Path("src/tilesector_polar_renderer.c")
s=renderer.read_text()
proto_anchor="\nvoid tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {"
proto_repl=("\n#ifdef __SDCC\n"
            "void tsp_polar_cast_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED;\n"
            "#endif\n\n"
            "void tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {")
s=replace_once(s,proto_anchor,proto_repl,"renderer cast-light prototype")
call_anchor="    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\ndone:"
call_repl=("    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\n"
           "#ifdef __SDCC\n"
           "    if(g_tspf_appearance_mode==0u)tsp_polar_cast_light(s,out_map);\n"
           "#endif\n"
           "done:")
s=replace_once(s,call_anchor,call_repl,"renderer cast-light call")
renderer.write_text(s)


# ---------------------------------------------------------------------------
# Tiny LUTs needed by the banked runtime. Cast-plane yaw tables come from the
# new PC bake. Gate tables below are also generated here on the PC, not solved
# on the Z80.
# ---------------------------------------------------------------------------
invz_lut=generated_c_array("k_tspf_invz","k_cast_invz")
sin=generated_int_array("k_tspf_sin_q7")
if len(sin)!=256: raise SystemExit(f"unexpected sin LUT size {len(sin)}")

def round_div_signed(n,d):
    return (n+d//2)//d if n>=0 else -(((-n)+d//2)//d)

gate_nf=[];gate_sf=[]
for yaw in range(256):
    sn=sin[yaw];cs=sin[(yaw+64)&255]
    gate_nf.append(cs)
    gate_sf.append(max(-127,min(127,round_div_signed((-sn)*4,5))))

gate_nf_c=c_i8("k_gate_nf_q7",gate_nf)
gate_sf_c=c_i8("k_gate_stepfac_q4",gate_sf)

runtime=f'''/* GENERATED by tools/apply_polar_cast_run_light_runtime.py.
 * Receiver-owned static illumination using Polar virtual wall-bottom runs.
 * No world polygon construction, polygon clipping, ray casting, or scan fill.
 */
#include <stdint.h>
#if defined(__SDCC)
#include <gbdk/platform.h>
#endif
#include "tilesector_polar.h"
#include "tilesector_polar_cast_plane_meta.h"

#if defined(__SDCC)
extern volatile uint8_t g_tspf_stage;
extern volatile uint8_t g_ts_render_stage;
extern uint8_t g_polar_nt_cov_cur[60];
extern uint8_t g_polar_nt_row_min[18];
extern uint8_t g_polar_nt_row_max[18];

#define CAST_SET_STAGE(v) do{{g_tspf_stage=(v);g_ts_render_stage=(v);}}while(0)
#define CAST_PLANE_COUNT 6u
#define CAST_GATE_A 4u
#define CAST_GATE_B 5u
#define CAST_FLOOR_FIRST_ROW 10u
#define CAST_BASE_FLOOR_WORD ((uint16_t)TSP_TILE_FLOOR)
#define CAST_LIT_FLOOR_WORD ((uint16_t)(TSP_TILE_FLOOR|TSP_ATTR_PALETTE))

static const uint16_t k_cast_row_base[TSP_ROWS]={{
    0u,20u,40u,60u,80u,100u,120u,140u,160u,
    180u,200u,220u,240u,260u,280u,300u,320u,340u
}};
static const uint8_t k_cast_nt_mask8[8]={{1u,2u,4u,8u,16u,32u,64u,128u}};

/* Cast anchors are authored portal vertices v2,v3,v6,v7. */
static const uint8_t k_cast_anchor_x[6]={{80u,80u,112u,112u,80u,112u}};
static const uint8_t k_cast_anchor_y[6]={{36u,64u,36u,64u,0u,0u}};
/* Desired illuminated side of n dot (P-anchor): 0=negative, 1=positive. */
static const uint8_t k_cast_lit_positive[6]={{0u,1u,1u,0u,0u,1u}};
static const uint8_t k_cast_floor_z[6]={{0u,0u,4u,4u,0u,4u}};
static const int8_t k_cast_gate_nx_q5[2]={{32,32}};
static const int8_t k_cast_gate_ny_q5[2]={{0,0}};

{invz_lut}
{gate_nf_c}
{gate_sf_c}

static int8_t g_cast_nf_q7[6];
static int8_t g_cast_sf_q4[6];
static uint8_t g_cast_yaw_cache=0xffu;

typedef struct CastScreenPlane {{
    int16_t q0;      /* signed inverse-depth Q6 at screen x=0 */
    int16_t step;    /* signed inverse-depth Q6 per 8-pixel column */
    uint8_t cam_lit; /* camera world point lies on illuminated side */
    uint8_t floor_z;
}} CastScreenPlane;

static CastScreenPlane g_cast_plane[6];

static int16_t cast_shr_signed(int16_t v,uint8_t n){{return v>=0?(int16_t)(v>>n):(int16_t)-(((-v)>>n));}}
static int8_t cast_clamp_s8(int16_t v,int8_t lo,int8_t hi){{if(v<lo)return lo;if(v>hi)return hi;return (int8_t)v;}}
static uint8_t cast_clamp_u8(int16_t v){{if(v<0)return 0u;if(v>255)return 255u;return (uint8_t)v;}}

/* Same exact cardinal/general plane-distance shape used by mature wall runs.
 * Returned d is n dot (anchor-camera) in Q4; camera plane sign is therefore
 * the opposite sign of d. */
static int16_t cast_plane_d_q4(uint8_t pi,int8_t nx,int8_t ny,const TSPState *s){{
    int16_t xi=(int16_t)(s->x_q4>>4),yi=(int16_t)(s->y_q4>>4);
    uint8_t fx=(uint8_t)(s->x_q4&15u),fy=(uint8_t)(s->y_q4&15u);
    int16_t dx=(int16_t)k_cast_anchor_x[pi]-xi,dy=(int16_t)k_cast_anchor_y[pi]-yi;
    int16_t whole=(int16_t)nx*dx+(int16_t)ny*dy;
    int16_t frac=(int16_t)nx*fx+(int16_t)ny*fy;
    return (int16_t)(cast_shr_signed(whole,1)-cast_shr_signed(frac,5));
}}

static uint8_t cast_inv_for_dq4(int16_t dq4){{
    uint16_t a=(uint16_t)(dq4<0?-dq4:dq4);uint8_t z,f,x0,x1;int16_t d;
    if(a<=(10u<<4))return 255u;
    if(a>=(127u<<4))return k_cast_invz[127];
    z=(uint8_t)(a>>4);f=(uint8_t)(a&15u);x0=k_cast_invz[z];x1=k_cast_invz[(uint8_t)(z+1u)];d=(int16_t)x1-(int16_t)x0;
    return (uint8_t)((int16_t)x0+cast_shr_signed((int16_t)(d*(int16_t)f+(d>=0?8:-8)),4));
}}

static void cast_prepare_plane(uint8_t pi,int8_t nx,int8_t ny,const TSPState *s){{
    int16_t d=cast_plane_d_q4(pi,nx,ny,s);
    uint8_t invd=cast_inv_for_dq4(d);
    int16_t iq=cast_shr_signed((int16_t)((int16_t)invd*(int16_t)g_cast_nf_q7[pi]),1);
    int16_t step=cast_shr_signed((int16_t)((int16_t)invd*(int16_t)g_cast_sf_q4[pi]),4);
    /* screen-depth plane tables are centred on x=80, the left edge of col10. */
    if(d<0){{iq=(int16_t)-iq;step=(int16_t)-step;}}
    iq=(int16_t)(iq-((step<<3)+(step<<1)));
    g_cast_plane[pi].q0=iq;
    g_cast_plane[pi].step=step;
    /* n dot (camera-anchor) is -d. */
    g_cast_plane[pi].cam_lit=(uint8_t)(((d<0)?1u:0u)==k_cast_lit_positive[pi]);
    g_cast_plane[pi].floor_z=k_cast_floor_z[pi];
}}

static int16_t cast_floor_y_from_q(int16_t q,uint8_t floor_z){{
    uint8_t inv,half;
    if(q<=0)return -32767;
    inv=cast_clamp_u8((int16_t)((q+32)>>6));
    half=(uint8_t)(inv>>1);
    if(floor_z)return (int16_t)(72+half-(half>>2));
    return (int16_t)(72+half);
}}

static uint8_t cast_plane_pass(const CastScreenPlane *p,int16_t ql,int16_t qr,uint8_t row){{
    int16_t qm=(int16_t)((ql+qr)>>1),yb;int16_t yc=(int16_t)(((uint16_t)row<<3)+4u);
    if(qm<=0)return p->cam_lit;
    yb=cast_floor_y_from_q(qm,p->floor_z);
    return p->cam_lit?(uint8_t)(yc>=yb):(uint8_t)(yc<yb);
}}

static uint8_t cast_plane_crosses_cell(const CastScreenPlane *p,int16_t ql,int16_t qr,uint8_t row,int16_t *yl,int16_t *yr){{
    int16_t lo=(int16_t)((uint16_t)row<<3),hi=(int16_t)(lo+7);
    if(ql<=0||qr<=0)return 0u;
    *yl=cast_floor_y_from_q(ql,p->floor_z);*yr=cast_floor_y_from_q(qr,p->floor_z);
    return (uint8_t)(((*yl>=lo&&*yl<=hi)||(*yr>=lo&&*yr<=hi)||(*yl<lo&&*yr>hi)||(*yr<lo&&*yl>hi))?1u:0u);
}}

static uint8_t cast_cell_unclaimed(uint8_t row,uint8_t col){{
    uint8_t ci=(uint8_t)(col+col+col+(row>>3));
    return (uint8_t)((g_polar_nt_cov_cur[ci]&k_cast_nt_mask8[row&7u])==0u);
}}

static void cast_put_cell(uint16_t *out,uint8_t row,uint8_t col,uint16_t word){{
    uint16_t idx=k_cast_row_base[row]+col;uint8_t ci=(uint8_t)(col+col+col+(row>>3));
    g_polar_nt_cov_cur[ci]|=k_cast_nt_mask8[row&7u];
    if(out[idx]!=word){{
        out[idx]=word;
        if(g_polar_nt_row_min[row]==0xffu||col<g_polar_nt_row_min[row])g_polar_nt_row_min[row]=col;
        if(col>g_polar_nt_row_max[row])g_polar_nt_row_max[row]=col;
    }}
}}

/* Shade-0 edge patterns are authored as base-floor above / lit-floor below in
 * palette 1. Vertical flip converts the same pattern to lit-above, so no new
 * VRAM patterns are needed. */
static uint16_t cast_edge_word(int16_t local_left,int8_t slope,uint8_t lit_below){{
    uint16_t attr=TSP_ATTR_PALETTE;uint8_t mag;int8_t off;
    if(!lit_below){{local_left=(int16_t)(7-local_left);slope=(int8_t)-slope;attr|=TSP_ATTR_FLIPY;}}
    if(slope<0){{mag=(uint8_t)(-slope);local_left=(int16_t)(local_left-mag);attr|=TSP_ATTR_FLIPX;}}else mag=(uint8_t)slope;
    if(mag>=TSP_EDGE_SLOPE_COUNT)mag=TSP_EDGE_SLOPE_COUNT-1u;
    off=cast_clamp_s8(local_left,TSP_EDGE_OFF_MIN,(int8_t)(TSP_EDGE_OFF_MIN+TSP_EDGE_OFF_COUNT-1));
    return (uint16_t)(TSP_TILE_EDGE(0u,(uint8_t)(off-TSP_EDGE_OFF_MIN),mag)|attr);
}}

static void cast_draw_receiver(uint16_t *out,uint8_t p0,uint8_t p1,uint8_t gate){{
    uint8_t c,row,k;int16_t ql[3],qr[3],yl[3],yr[3];uint8_t pass[3],cross[3];
    uint8_t ids[3];ids[0]=p0;ids[1]=p1;ids[2]=gate;
    for(c=0u;c<TSP_COLS;++c){{
        for(k=0u;k<3u;++k){{
            const CastScreenPlane *p=&g_cast_plane[ids[k]];
            ql[k]=(int16_t)(p->q0+(int16_t)((int16_t)p->step*(int16_t)c));
            qr[k]=(int16_t)(ql[k]+p->step);
        }}
        for(row=CAST_FLOOR_FIRST_ROW;row<TSP_ROWS;++row){{
            uint8_t all=1u,cross_count=0u,cross_id=0xffu,others=1u;
            if(!cast_cell_unclaimed(row,c))continue;
            for(k=0u;k<3u;++k){{
                const CastScreenPlane *p=&g_cast_plane[ids[k]];
                pass[k]=cast_plane_pass(p,ql[k],qr[k],row);if(!pass[k])all=0u;
                cross[k]=cast_plane_crosses_cell(p,ql[k],qr[k],row,&yl[k],&yr[k]);
                if(cross[k]){{++cross_count;cross_id=k;}}
            }}
            if(all&&cross_count==0u){{cast_put_cell(out,row,c,CAST_LIT_FLOOR_WORD);continue;}}
            if(cross_count==1u){{
                for(k=0u;k<3u;++k)if(k!=cross_id&&!pass[k])others=0u;
                if(others){{
                    const CastScreenPlane *p=&g_cast_plane[ids[cross_id]];
                    int16_t rowtop=(int16_t)((uint16_t)row<<3);
                    int8_t slope=cast_clamp_s8((int16_t)(yr[cross_id]-yl[cross_id]),-7,7);
                    cast_put_cell(out,row,c,cast_edge_word((int16_t)(yl[cross_id]-rowtop),slope,p->cam_lit));
                    continue;
                }}
            }}
            /* At a corner where two baked bounds share one 8x8 tile, centre
             * classification is the deterministic tie break. This is a local
             * tile quantisation event, not a geometric hole. */
            if(all)cast_put_cell(out,row,c,CAST_LIT_FLOOR_WORD);
        }}
    }}
}}

void tsp_polar_cast_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED {{
    uint8_t i;
    CAST_SET_STAGE(5u);
    if(s->yaw!=g_cast_yaw_cache){{
        tsp_polar_castplane_load(s->yaw,g_cast_nf_q7,g_cast_sf_q4);
        g_cast_nf_q7[CAST_GATE_A]=k_gate_nf_q7[s->yaw];g_cast_sf_q4[CAST_GATE_A]=k_gate_stepfac_q4[s->yaw];
        g_cast_nf_q7[CAST_GATE_B]=k_gate_nf_q7[s->yaw];g_cast_sf_q4[CAST_GATE_B]=k_gate_stepfac_q4[s->yaw];
        g_cast_yaw_cache=s->yaw;
    }}
    for(i=0u;i<4u;++i)cast_prepare_plane(i,k_tspf_cast_nx_q5[i],k_tspf_cast_ny_q5[i],s);
    cast_prepare_plane(CAST_GATE_A,k_cast_gate_nx_q5[0],k_cast_gate_ny_q5[0],s);
    cast_prepare_plane(CAST_GATE_B,k_cast_gate_nx_q5[1],k_cast_gate_ny_q5[1],s);
    CAST_SET_STAGE(6u);cast_draw_receiver(out_map,0u,1u,CAST_GATE_A);
    CAST_SET_STAGE(7u);cast_draw_receiver(out_map,2u,3u,CAST_GATE_B);
    CAST_SET_STAGE(0u);
}}
#endif
'''
Path("src/tilesector_polar_cast_light_runtime.c").write_text(runtime)


# ---------------------------------------------------------------------------
# Makefile: add the generated compact plane object and separately banked runtime
# object. The workflow emits build/generated/polar_cast_plane before make.
# ---------------------------------------------------------------------------
mk=Path("Makefile");m=mk.read_text()
flags_anchor="POLAR_GGFLAGS = $(filter-out -Wm-yo4,$(GGFLAGS)) -Wm-yo$(POLAR_ROM_BANKS) -I$(POLAR_PROJ_GEN_DIR) -I$(POLAR_DEPTHPLANE_GEN_DIR)"
flags_repl=flags_anchor+" -Ibuild/generated/polar_cast_plane"
m=replace_once(m,flags_anchor,flags_repl,"cast-plane include path")
obj_anchor="POLAR_GG_OBJS := build/main_tilesector_polar_gg.o build/tilesector_polar_motion_gg.o build/tilesector_polar_renderer_gg.o build/tilesector_polar_ntstate_gg.o build/tilesector_polar_materialize_gg.o $(POLAR_NTUPLOAD_OBJ)"
obj_repl=obj_anchor+" build/tilesector_polar_cast_light_runtime_gg.o build/tilesector_polar_castplane_gg.o"
m=replace_once(m,obj_anchor,obj_repl,"cast-light objects")
rule_anchor="build/tilesector_polar_renderer_gg.o: src/tilesector_polar_renderer.c $(POLAR_PROJ_META) $(POLAR_DEPTHPLANE_HDR) | build\n\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n"
rule_repl=rule_anchor+("\nbuild/tilesector_polar_cast_light_runtime_gg.o: src/tilesector_polar_cast_light_runtime.c build/generated/polar_cast_plane/tilesector_polar_cast_plane_meta.h | build\n"
                       "\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n\n"
                       "build/tilesector_polar_castplane_gg.o: build/generated/polar_cast_plane/tilesector_polar_castplane.c build/generated/polar_cast_plane/tilesector_polar_cast_plane_meta.h | build\n"
                       "\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ build/generated/polar_cast_plane/tilesector_polar_castplane.c\n")
m=replace_once(m,rule_anchor,rule_repl,"cast-light build rules")
mk.write_text(m)


# ---------------------------------------------------------------------------
# VDP palette/pattern semantics. Palette 0 floor colour is the normal unlit
# base. Palette 1 index C_FLOOR is brighter. Shade-zero edge patterns contain
# only C_OUT/C_FLOOR, no black contour, and palette 1 maps those to base/lit.
# Existing geometry uses shade 1 in appearance mode 0, so the shade-zero family
# remains free without allocating a single extra 32-byte VRAM pattern.
# ---------------------------------------------------------------------------
main=Path("src/main_tilesector_polar_gg.c");t=main.read_text()
pal_anchor="    RGB(0,0,0),RGB(2,2,3),RGB(2,2,3),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
pal_repl="    RGB(0,0,0),RGB(2,2,3),RGB(5,5,7),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
t=replace_once(t,pal_anchor,pal_repl,"palette1 lit floor")
edge_anchor="static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
edge_repl="static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c;if(shade==0u)c=(int8_t)y<line?C_OUT:C_FLOOR;else c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
t=replace_once(t,edge_anchor,edge_repl,"shade-zero lit boundary pattern")
main.write_text(t)

print(BRANCH_NOTE)
print("RUNTIME_GEOMETRY=FOUR_CAST_PLANES_PLUS_TWO_RECEIVER_GATES")
print("RUNTIME_SHADOW_POLYGONS=0")
print("RUNTIME_POLYGON_CLIPS=0")
print("RUNTIME_WORLD_RAY_CASTS=0")
print("FLOOR_ENDPOINT_BEARING_BYTES=0")
print("NEW_VRAM_PATTERNS=0")
print("BASE_FLOOR=PALETTE0_C_FLOOR")
print("LIT_FLOOR=PALETTE1_C_FLOOR")
print("BOUNDARY=SHADE0_EDGE_FAMILY_PALETTE1")
print("WALL_RECEIVER_SPLIT=NOT_YET_IN_THIS_CHECKPOINT")
