#!/usr/bin/env python3
"""Apply the division-free screen-affine floor-light runtime experiment.

Builds the lighting pass as one separately BANKED object and leaves the clean
Polar renderer source as the baseline for same-commit A/B profiling. Static
shadow polygons are represented by screen-affine half-planes in the included
kernel. Runtime lighting allocates no new VRAM patterns and carries no camera
position/bearing field or reciprocal/depth LUT; only a 256-entry Q9 yaw sine
LUT (512 bytes) is embedded in the lighting object.
"""
from pathlib import Path
import math


def replace_once(text: str, old: str, new: str, label: str) -> str:
    n = text.count(old)
    if n != 1:
        raise SystemExit(f"{label}: expected exactly one anchor, found {n}")
    return text.replace(old, new, 1)


# 1) One BANKED call from the mature renderer.
renderer = Path("src/tilesector_polar_renderer.c")
s = renderer.read_text()
proto_anchor = "\nvoid tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {"
proto_repl = (
    "\n#ifdef __SDCC\n"
    "void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED;\n"
    "#endif\n\n"
    "void tsp_polar_render(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS],TSPColumn cols[TSP_COLS]) BANKED {"
)
s = replace_once(s, proto_anchor, proto_repl, "renderer light prototype")
call_anchor = "    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\ndone:"
call_repl = "    TSPF_SET_STAGE(4u);for(i=0;i<count;++i)draw_run(out_map,cols,&g_runs[g_run_order[i]]);\n#ifdef __SDCC\n    if(g_tspf_appearance_mode==0u)tsp_polar_floor_light(s,out_map);\n#endif\ndone:"
s = replace_once(s, call_anchor, call_repl, "renderer light call")
renderer.write_text(s)


# 2) Self-contained lighting object. Q9 is the measured integer sweet spot:
#    Q8 mean raw oracle error 0.1274%, Q9 0.0716%, Q10 0.0608% but Q10 pushes
#    the natural affine range beyond convenient signed-32 arithmetic.
inc = Path("src/tilesector_polar_floor_light_affine.inc").read_text()
fn_old = "static void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]){"
fn_new = "void tsp_polar_floor_light(const TSPState *s,uint16_t out_map[TSP_MAP_CELLS]) BANKED {"
inc = replace_once(inc, fn_old, fn_new, "affine floor-light exported BANKED entry")
vals = [int(round(math.sin(i * math.tau / 256.0) * 511.0)) for i in range(256)]
rows = [",".join(str(v) for v in vals[i:i+16]) for i in range(0, 256, 16)]
sin_lut = "static const int16_t k_fl_sin_q9[256] = {\n    " + ",\n    ".join(rows) + "\n};"

runtime_src = f'''/* GENERATED by tools/apply_affine_floor_light_runtime.py.
 * Division-free free-camera floor lighting: one BANKED call per rendered update.
 * No new VRAM patterns. No position/bearing field. No reciprocal/depth LUT. */
#include <stdint.h>
#if defined(__SDCC)
#include <gbdk/platform.h>
#endif
#include "tilesector_polar.h"

#if defined(__SDCC)
extern uint8_t g_polar_nt_cov_cur[60];
extern uint8_t g_polar_nt_row_min[18];
extern uint8_t g_polar_nt_row_max[18];

static const uint16_t k_fl_row_base[TSP_ROWS] = {{
    0u,20u,40u,60u,80u,100u,120u,140u,160u,
    180u,200u,220u,240u,260u,280u,300u,320u,340u
}};
static const uint8_t k_fl_nt_mask8[8] = {{1u,2u,4u,8u,16u,32u,64u,128u}};
{sin_lut}

static void flrt_put_cell(uint16_t *out,uint8_t row,uint8_t col,uint16_t word){{
    uint16_t idx=k_fl_row_base[row]+col;
    uint8_t cov_i=(uint8_t)(col+col+col+(row>>3));
    g_polar_nt_cov_cur[cov_i]|=k_fl_nt_mask8[row&7u];
    if(out[idx]!=word){{
        out[idx]=word;
        if(g_polar_nt_row_min[row]==0xffu||col<g_polar_nt_row_min[row])g_polar_nt_row_min[row]=col;
        if(col>g_polar_nt_row_max[row])g_polar_nt_row_max[row]=col;
    }}
}}

#define put_cell flrt_put_cell
#define k_nt_mask8 k_fl_nt_mask8
{inc}
#undef put_cell
#undef k_nt_mask8
#endif /* __SDCC */
'''
Path("src/tilesector_polar_floor_light_runtime.c").write_text(runtime_src)


# 3) One independently bankable object.
mk = Path("Makefile")
ms = mk.read_text()
obj_anchor = "POLAR_GG_OBJS := build/main_tilesector_polar_gg.o build/tilesector_polar_motion_gg.o build/tilesector_polar_renderer_gg.o build/tilesector_polar_ntstate_gg.o build/tilesector_polar_materialize_gg.o $(POLAR_NTUPLOAD_OBJ)"
obj_repl = obj_anchor + " build/tilesector_polar_floor_light_runtime_gg.o"
ms = replace_once(ms, obj_anchor, obj_repl, "Polar object list")
rule_anchor = "build/tilesector_polar_renderer_gg.o: src/tilesector_polar_renderer.c $(POLAR_PROJ_META) $(POLAR_DEPTHPLANE_HDR) | build\n\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n"
rule_repl = rule_anchor + "\nbuild/tilesector_polar_floor_light_runtime_gg.o: src/tilesector_polar_floor_light_runtime.c | build\n\t$(LCC) $(POLAR_GGFLAGS) $(POLAR_CFLAGS) -c -o $@ $<\n"
ms = replace_once(ms, rule_anchor, rule_repl, "floor-light object rule")
mk.write_text(ms)


# 4) Zero-new-pattern palette/tile authoring, identical semantics to the mature
#    runtime-light experiment: shade-0 becomes a two-colour floor boundary and
#    palette 1 swaps normal/shadow floor colours.
main = Path("src/main_tilesector_polar_gg.c")
m = main.read_text()
pal_anchor = "    RGB(0,0,0),RGB(2,2,3),RGB(2,2,3),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
pal_repl = "    RGB(0,0,0),RGB(2,2,3),RGB(1,1,3),RGB(3,4,6),RGB(6,7,9),RGB(10,11,13),"
m = replace_once(m, pal_anchor, pal_repl, "palette-1 shadow slot")
edge_anchor = "static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
edge_repl = "static void emit_edge(uint8_t shade,uint8_t oi,uint8_t si){uint8_t x,y,color=shade_color(shade);int8_t off=(int8_t)TSP_EDGE_OFF_MIN+(int8_t)oi;clear_tile();for(y=0;y<8u;++y)for(x=0;x<8u;++x){int8_t line=(int8_t)(off+k_edge_lut[si][x]);uint8_t c;if(shade==0u)c=(int8_t)y<line?C_OUT:C_FLOOR;else c=(int8_t)y<line?C_OUT:((int8_t)y==line?C_BLACK:color);paint_pixel(x,y,c);}set_bkg_4bpp_data(TSP_TILE_EDGE(shade,oi,si),1u,g_tile);}"
m = replace_once(m, edge_anchor, edge_repl, "shade-zero floor edge authoring")
toggle_anchor = "    if(pressed&J_START){if(pad&J_B)g_tspf_appearance_mode=0u;else if(pad&J_A)g_tspf_appearance_mode=2u;else {++g_tspf_appearance_mode;if(g_tspf_appearance_mode>2u)g_tspf_appearance_mode=0u;}}"
toggle_repl = "    if(pressed&J_START)g_tspf_appearance_mode=0u;"
m = replace_once(m, toggle_anchor, toggle_repl, "appearance-mode pin")
main.write_text(m)

print("AFFINE_FLOOR_LIGHT_RUNTIME_PATCH=APPLIED")
print("LIGHT_TRANSLATION_UNIT=SEPARATE_BANKED_OBJECT")
print("BANKED_CALLS_PER_RENDERED_UPDATE=1")
print("AFFINE_STATIC_LINES=11")
print("CAST_EDGES=4")
print("CAMERA_POSITION=FULL_Q4")
print("YAW_TRIG=Q9_512_BYTES")
print("LIGHT_POSITION_FIELD_BYTES=0")
print("LIGHT_RECIPROCAL_BYTES=0")
print("NEW_VRAM_PATTERNS=0")
