#!/usr/bin/env python3
"""Generate a banked authoritative physical-vertex depth helper.

Wall-plane endpoint projection loses information when inv_for_dq4() saturates a
very small perpendicular plane distance before the grazing-angle dot product is
applied. A shared corner must instead be projected from the authored vertex
itself: camera-forward = dot(vertex-player, camera-forward-axis), followed by
the normal near/far reciprocal clamp exactly once.

This helper is deliberately isolated in its own ROM bank. Shared physical
corners are sparse, so a banked call is preferable to spending the final bytes
of renderer bank 255 before the true-X compositor is proven.
"""
from __future__ import annotations
import argparse
import pathlib
import re

def arr(text,name):
    m=re.search(r"static\s+const\s+[^;=]+?\b"+re.escape(name)+r"\s*\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not m:
        raise SystemExit("missing generated array "+name)
    return [int(x,0) for x in re.findall(r"-?0x[0-9A-Fa-f]+|-?\d+",m.group(1))]

def shr0(v,n):
    return v>>n if v>=0 else -((-v)>>n)

def emit(name,ctype,data,per=24):
    out=[f"static const {ctype} {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--map-inc",required=True)
    ap.add_argument("--out-dir",required=True)
    ap.add_argument("--bank",type=int,required=True)
    args=ap.parse_args()

    text=pathlib.Path(args.map_inc).read_text()
    vx=arr(text,"k_tspf_vx")
    vy=arr(text,"k_tspf_vy")
    sin=arr(text,"k_tspf_sin_q7")
    invz=arr(text,"k_tspf_invz")
    if len(vx)!=len(vy) or len(sin)!=256:
        raise SystemExit("vertex/sine source shape mismatch")

    def inv_for_abs_q4(a):
        if a <= (10<<4):
            return 255
        if a >= (127<<4):
            return invz[127]
        z=a>>4
        f=a&15
        x0=invz[z]
        x1=invz[z+1]
        d=x1-x0
        return x0+shr0(d*f+(8 if d>=0 else -8),4)

    invq=[inv_for_abs_q4(a) for a in range((127<<4)+1)]
    out=pathlib.Path(args.out_dir)
    out.mkdir(parents=True,exist_ok=True)
    (out/"e1env_vertex_depth.h").write_text("""/* GENERATED by tools/e1env_vertex_depth_bank.py. */
#ifndef E1ENV_VERTEX_DEPTH_H
#define E1ENV_VERTEX_DEPTH_H
#include <stdint.h>
#include <gbdk/platform.h>
#define E1ENV_VERTEX_DEPTH 1u
uint8_t e1env_vertex_half(uint8_t vid,int16_t x_q4,int16_t y_q4,uint8_t yaw) BANKED;
#endif
""")
    src=f"""/* GENERATED by tools/e1env_vertex_depth_bank.py. */
#include <stdint.h>
#include <gbdk/platform.h>
#pragma bank {args.bank}
BANKREF(e1env_vertex_depth)

{emit("k_vx","uint8_t",vx)}
{emit("k_vy","uint8_t",vy)}
{emit("k_sin","int8_t",sin,32)}
{emit("k_invq4","uint8_t",invq,32)}

/* Returns FULL half-height (inverse camera-forward depth >> 1).
 * Visible envelope vertices are in front of the camera. Keep the <=0 guard
 * defensive so a future caller cannot index the reciprocal table backwards.
 *
 * int32_t is intentional in this first correctness rung: world Q4 deltas can
 * exceed 8 bits. Shared corners are sparse; profile this exact cost before
 * replacing it with a hand-decomposed 8x8 Z80 dot product.
 */
uint8_t e1env_vertex_half(uint8_t vid,int16_t x_q4,int16_t y_q4,uint8_t yaw) BANKED {{
    int16_t dx=(int16_t)(((int16_t)k_vx[vid]<<4)-x_q4);
    int16_t dy=(int16_t)(((int16_t)k_vy[vid]<<4)-y_q4);
    int16_t sn=k_sin[yaw];
    int16_t cs=k_sin[(uint8_t)(yaw+64u)];
    int32_t q=(int32_t)dx*(int32_t)cs+(int32_t)dy*(int32_t)sn;
    uint16_t z;
    if(q<=0) return 127u;
    z=(uint16_t)(q>>7);
    if(z>2032u) z=2032u;
    return (uint8_t)(k_invq4[z]>>1);
}}
"""
    (out/"e1env_vertex_depth.c").write_text(src)
    print(f"E1ENV_VERTEX_DEPTH bank={args.bank} vertices={len(vx)} data_bytes={len(vx)+len(vy)+len(sin)+len(invq)}")

if __name__=="__main__":
    main()
