#!/usr/bin/env python3
"""Generate a bank-local exact-envelope screen-depth evaluator.

The hot renderer currently evaluates two endpoint rays per visible run.  For a
straight wall, inverse camera depth is affine in screen x.  This module bakes
normal/yaw coefficients into ROM and returns the final Q6 start+step for one
coarse run in a single BANKED call.

To keep the banked helper from falling back to SDCC's generic 16-bit multiply,
uint8 * int8 products use an exact quarter-square identity:

    a*b = floor((a+b)^2/4) - floor((a-b)^2/4)

(a+b) and (a-b) always have the same parity, so the floor terms cancel exactly.)
The quarter-square table is only 383 uint16 entries.
"""
from __future__ import annotations
import argparse
import pathlib
import re

def arr(text,name):
    m=re.search(r"static\s+const\s+[^;=]+?\b"+re.escape(name)+r"\s*\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not m:
        raise SystemExit("missing generated array "+name)
    return [int(x,0) for x in re.findall(r"-?0x[0-9A-Fa-f]+|-?\d+",m.group(1))]

def shr0(v,n):
    return v>>n if v>=0 else -((-v)>>n)

def round_div_signed(n,d):
    return (n+d//2)//d if n>=0 else -(((-n)+d//2)//d)

def emit_i8_rows(name,rows):
    out=[f"static const int8_t {name}[{len(rows)}][256] = {{"]
    for row in rows:
        out.append("    {")
        for i in range(0,256,16):
            out.append("        "+", ".join(str(v) for v in row[i:i+16])+",")
        out.append("    },")
    out.append("};")
    return "\n".join(out)

def emit_u8(name,data,per=20):
    out=[f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def emit_u16(name,data,per=12):
    out=[f"static const uint16_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--map-inc",required=True)
    ap.add_argument("--out-dir",required=True)
    ap.add_argument("--bank",type=int,default=242)
    a=ap.parse_args()

    text=pathlib.Path(a.map_inc).read_text()
    nx=arr(text,"k_tspf_nx_q5")
    ny=arr(text,"k_tspf_ny_q5")
    sin=arr(text,"k_tspf_sin_q7")
    normals=[]; cls=[]
    for pair in zip(nx,ny):
        if pair not in normals: normals.append(pair)
        cls.append(normals.index(pair))

    nf=[]; sf=[]
    for cx,cy in normals:
        rn=[]; rs=[]
        for yaw in range(256):
            sn=sin[yaw]; cs=sin[(yaw+64)&255]
            forward=shr0(cx*cs+cy*sn,5)
            side=shr0(-cx*sn+cy*cs,5)
            forward=max(-127,min(127,forward))
            side=max(-127,min(127,side))
            rn.append(forward)
            # Q4 coefficient: runtime step_q6 = invd * sf / 16.
            rs.append(max(-127,min(127,round_div_signed(side*4,5))))
        nf.append(rn); sf.append(rs)

    qs=[(i*i)//4 for i in range(383)]
    outdir=pathlib.Path(a.out_dir); outdir.mkdir(parents=True,exist_ok=True)

    hdr=f"""/* GENERATED by tools/e1env_depthplane_bank.py. */
#ifndef E1ENV_DEPTHPLANE_BANK_H
#define E1ENV_DEPTHPLANE_BANK_H
#include <stdint.h>
#include <gbdk/platform.h>
#define E1ENV_DEPTHPLANE_BANK 1u
extern int16_t g_e1env_dp_iq;
extern int16_t g_e1env_dp_step;
extern uint8_t g_e1env_dp_mid;
uint8_t e1env_depthplane_eval(uint8_t sid,uint8_t invd,uint8_t c0,uint8_t c1,uint8_t yaw) BANKED;
#endif
"""
    src=f"""/* GENERATED by tools/e1env_depthplane_bank.py. */
#include <stdint.h>
#include <gbdk/platform.h>
#pragma bank {a.bank}
BANKREF(e1env_depthplane_bank)

{emit_u8("k_cls",cls)}

{emit_i8_rows("k_nf_q7",nf)}

{emit_i8_rows("k_sf_q4",sf)}

{emit_u16("k_qsquare",qs)}

int16_t g_e1env_dp_iq;
int16_t g_e1env_dp_step;
uint8_t g_e1env_dp_mid;

static int16_t mul_u8_s8(uint8_t a,int8_t b) {{
    int16_t sb=(int16_t)b;
    int16_t s=(int16_t)a+sb;
    int16_t d=(int16_t)a-sb;
    uint16_t as=(uint16_t)(s<0 ? -s : s);
    uint16_t ad=(uint16_t)(d<0 ? -d : d);
    return (int16_t)(k_qsquare[as]-k_qsquare[ad]);
}}
static int16_t shr1z(int16_t v) {{
    return v>=0 ? (int16_t)(v>>1) : (int16_t)-(((-v)>>1));
}}
static int16_t shr4z(int16_t v) {{
    return v>=0 ? (int16_t)(v>>4) : (int16_t)-(((-v)>>4));
}}

uint8_t e1env_depthplane_eval(uint8_t sid,uint8_t invd,uint8_t c0,uint8_t c1,uint8_t yaw) BANKED {{
    uint8_t cl=k_cls[sid],i,n=(uint8_t)(c1-c0+1u);
    int16_t iq=shr1z(mul_u8_s8(invd,k_nf_q7[cl][yaw]));
    int16_t step=shr4z(mul_u8_s8(invd,k_sf_q4[cl][yaw]));
    int16_t endq,midq;

    if(c0<10u) for(i=c0;i<10u;++i) iq=(int16_t)(iq-step);
    else for(i=10u;i<c0;++i) iq=(int16_t)(iq+step);

    endq=iq;
    for(i=0u;i<n;++i) endq=(int16_t)(endq+step);

    if((iq<0 && endq>0)||(iq>0 && endq<0)) return 0u;
    if(iq<0 || endq<0) {{
        iq=(int16_t)-iq;
        endq=(int16_t)-endq;
        step=(int16_t)-step;
    }}

    midq=(int16_t)((iq+endq)>>1);
    g_e1env_dp_iq=iq;
    g_e1env_dp_step=step;
    if(midq<=0) g_e1env_dp_mid=0u;
    else if(midq>=16352) g_e1env_dp_mid=255u;
    else g_e1env_dp_mid=(uint8_t)((midq+32)>>6);
    return 1u;
}}
"""
    (outdir/"e1env_depthplane_bank.h").write_text(hdr)
    (outdir/"e1env_depthplane_bank.c").write_text(src)
    bytes_=len(cls)+sum(map(len,nf))+sum(map(len,sf))+2*len(qs)
    print(f"E1ENV_DEPTHPLANE_BANK bank={a.bank} normal_classes={len(normals)} data_bytes={bytes_}")

if __name__=="__main__":
    main()
