#!/usr/bin/env python3
"""Generate exact ROM endpoint-depth evaluators for the Q4 envelope renderer.

Runtime inv_at_invd() currently recomputes wall-normal dot products, trigonometry
lookups, secant correction and four generic multiplies for every visible run.
For exact-envelope runs the sample rays are always one of the 21 baked coarse
column edges.  That makes the expensive angular part a finite ROM vocabulary.

For each unique wall-normal class, yaw and coarse edge this generator stores the
EXACT abs(dot) byte used by inv_at_invd().  sec(rel) is only 21 bytes. Runtime
then reproduces the same two rounded products with an exact quarter-square
uint8 multiply, so endpoint inverse depths stay bit-identical to the existing
path while the Z80 trades arithmetic for ROM reads.

Two normal classes fit in one 16 KiB bank; twelve classes therefore use six
banks. This is intentionally ROM-hungry after the exact-Q4 index compression
reclaimed roughly a hundred banks.
"""
from __future__ import annotations
import argparse
import pathlib
import re

EDGES=(-512,-479,-442,-400,-355,-305,-251,-193,-132,-69,-4,
        61,125,187,245,299,350,396,438,476,506)

def arr(text,name):
    m=re.search(r"static\s+const\s+[^;=]+?\b"+re.escape(name)+r"\s*\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not m:
        raise SystemExit("missing generated array "+name)
    return [int(x,0) for x in re.findall(r"-?0x[0-9A-Fa-f]+|-?\d+",m.group(1))]

def shr0(v,n):
    return v>>n if v>=0 else -((-v)>>n)

def emit_u8(name,data,per=21):
    out=[f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def emit_u16(name,data,per=12):
    out=[f"static const uint16_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def dot_for(nx,ny,yaw,rel,sin):
    wb=((yaw<<4)+rel)&4095
    bi=(wb>>4)&255
    sn=sin[bi]
    cs=sin[(bi+64)&255]
    if ny==0 and (nx==32 or nx==-32):
        dot=cs
    elif nx==0 and (ny==32 or ny==-32):
        dot=sn
    else:
        dot=shr0(nx*cs+ny*sn,5)
    dot=abs(dot)
    return min(127,dot)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--map-inc",required=True)
    ap.add_argument("--out-dir",required=True)
    ap.add_argument("--bank-base",type=int,default=236)
    args=ap.parse_args()

    text=pathlib.Path(args.map_inc).read_text()
    nx=arr(text,"k_tspf_nx_q5")
    ny=arr(text,"k_tspf_ny_q5")
    sin=arr(text,"k_tspf_sin_q7")
    sec=arr(text,"k_tspf_sec_q7")
    normals=[]; cls=[]
    for p in zip(nx,ny):
        if p not in normals: normals.append(p)
        cls.append(normals.index(p))
    if len(normals)>12:
        raise SystemExit(f"expected <=12 normal classes, got {len(normals)}")

    edge_sec=[sec[abs(r)] for r in EDGES]
    qs=[(i*i)//4 for i in range(511)]

    outdir=pathlib.Path(args.out_dir); outdir.mkdir(parents=True,exist_ok=True)
    hdr=[
        "/* GENERATED by tools/e1env_depth_edges_bank.py. */",
        "#ifndef E1ENV_DEPTH_EDGES_BANK_H",
        "#define E1ENV_DEPTH_EDGES_BANK_H",
        "#include <stdint.h>",
        "#include <gbdk/platform.h>",
        "#define E1ENV_DEPTH_EDGES_BANK 1u",
        emit_u8("k_e1env_depth_class",cls,20),
        "extern uint8_t g_e1env_depth_inv0;",
        "extern uint8_t g_e1env_depth_inv1;",
        "extern uint8_t g_e1env_depth_mid;",
    ]

    bank_count=(len(normals)+1)//2
    for bi in range(bank_count):
        hdr.append(f"uint8_t e1env_depth_edges_{bi}(uint8_t local_cls,uint8_t yaw,uint8_t c0,uint8_t c1,uint8_t invd) BANKED;")
    hdr += ["#endif",""]
    (outdir/"e1env_depth_edges_bank.h").write_text("\n".join(hdr))

    for bank_i in range(bank_count):
        classes=list(range(bank_i*2,min(bank_i*2+2,len(normals))))
        dots=[]
        for ci in classes:
            cx,cy=normals[ci]
            for yaw in range(256):
                for rel in EDGES:
                    dots.append(dot_for(cx,cy,yaw,rel,sin))
        # Pad a final singleton bank to two logical classes so index arithmetic
        # remains identical. (Normally E1M1 has an even class count.)
        if len(classes)==1:
            dots.extend([0]*(256*len(EDGES)))

        fn=f"e1env_depth_edges_{bank_i}"
        bridge_defs=("uint8_t g_e1env_depth_inv0;\n"
                     "uint8_t g_e1env_depth_inv1;\n"
                     "uint8_t g_e1env_depth_mid;") if bank_i==0 else (
                     "extern uint8_t g_e1env_depth_inv0;\n"
                     "extern uint8_t g_e1env_depth_inv1;\n"
                     "extern uint8_t g_e1env_depth_mid;")
        src=f"""/* GENERATED by tools/e1env_depth_edges_bank.py. */
#include <stdint.h>
#include <gbdk/platform.h>
#pragma bank {args.bank_base+bank_i}
BANKREF(e1env_depth_edges_{bank_i})

{emit_u8("k_dot",dots,21)}

{emit_u8("k_sec",edge_sec,21)}

{emit_u16("k_qsquare",qs,12)}

{bridge_defs}

static uint16_t mul8u(uint8_t a,uint8_t b) {{
    uint16_t s=(uint16_t)a+(uint16_t)b;
    uint16_t d=(uint16_t)(a>b ? a-b : b-a);
    return (uint16_t)(k_qsquare[s]-k_qsquare[d]);
}}
static uint8_t eval_one(uint8_t dot,uint8_t edge,uint8_t invd) {{
    uint16_t p=mul8u(invd,dot);
    uint16_t q=(uint16_t)((p+64u)>>7);
    p=mul8u((uint8_t)q,k_sec[edge]);
    q=(uint16_t)((p+64u)>>7);
    return (uint8_t)(q>255u ? 255u : q);
}}

uint8_t {fn}(uint8_t local_cls,uint8_t yaw,uint8_t c0,uint8_t c1,uint8_t invd) BANKED {{
    uint16_t base=(uint16_t)(((uint16_t)local_cls<<8)+(uint16_t)yaw)*21u;
    uint8_t a=eval_one(k_dot[base+c0],c0,invd);
    uint8_t e=(uint8_t)(c1+1u);
    uint8_t b=eval_one(k_dot[base+e],e,invd);
    g_e1env_depth_inv0=a;
    g_e1env_depth_inv1=b;
    g_e1env_depth_mid=(uint8_t)(((uint16_t)a+(uint16_t)b)>>1);
    return 1u;
}}
"""
        (outdir/f"{fn}.c").write_text(src)

    data_bytes=bank_count*(2*256*21 + 21 + 2*len(qs))
    print(f"E1ENV_DEPTH_EDGES banks={bank_count} bank_range={args.bank_base}..{args.bank_base+bank_count-1} "
          f"normal_classes={len(normals)} approx_data_bytes={data_bytes}")

if __name__=="__main__":
    main()
