#!/usr/bin/env python3
"""Compile E1M1 wall geometry into canonical map-plane metadata.

The runtime does not need to rediscover a normal and anchor for grid-authored
walls.  Orthogonal walls become X=C or Y=C. True 45-degree walls become one of
X+Y=C / X-Y=C and sign variants.  Only legacy arbitrary-angle geometry keeps
the generic normal-dot-product path.
"""
from __future__ import annotations
import argparse
import pathlib
import re

GENERIC=0
X_POS=1
X_NEG=2
Y_POS=3
Y_NEG=4
XPYP=5
XPYN=6
XNYP=7
XNYN=8

def arr(text,name):
    m=re.search(r"static\s+const\s+[^;=]+?\b"+re.escape(name)+r"\s*\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not m:
        raise SystemExit("missing generated array "+name)
    return [int(x,0) for x in re.findall(r"-?0x[0-9A-Fa-f]+|-?\d+",m.group(1))]

def emit(ctype,name,data,per=16):
    out=[f"static const {ctype} {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--map-inc",required=True)
    ap.add_argument("--out",required=True)
    a=ap.parse_args()
    text=pathlib.Path(a.map_inc).read_text()
    vx=arr(text,"k_tspf_vx"); vy=arr(text,"k_tspf_vy")
    anchor=arr(text,"k_tspf_seg_anchor")
    nx=arr(text,"k_tspf_nx_q5"); ny=arr(text,"k_tspf_ny_q5")
    if not(len(anchor)==len(nx)==len(ny)):
        raise SystemExit("surface-array length mismatch")

    ops=[]; const=[]; counts={k:0 for k in range(9)}
    for sid,(axid,qx,qy) in enumerate(zip(anchor,nx,ny)):
        x=vx[axid]; y=vy[axid]
        op=GENERIC; c=0
        if qx==32 and qy==0: op,c=X_POS,x
        elif qx==-32 and qy==0: op,c=X_NEG,x
        elif qx==0 and qy==32: op,c=Y_POS,y
        elif qx==0 and qy==-32: op,c=Y_NEG,y
        elif abs(qx)==23 and abs(qy)==23:
            sx=1 if qx>0 else -1
            sy=1 if qy>0 else -1
            if sx>0 and sy>0: op=XPYP
            elif sx>0 and sy<0: op=XPYN
            elif sx<0 and sy>0: op=XNYP
            else: op=XNYN
            c=sx*x+sy*y
        ops.append(op); const.append(c); counts[op]+=1

    hdr=[
        "/* GENERATED by tools/e1env_plane_meta.py. */",
        "#ifndef E1ENV_PLANE_META_H",
        "#define E1ENV_PLANE_META_H",
        "#include <stdint.h>",
        "#define E1ENV_PLANE_META 1u",
        "#define E1ENV_PLANE_GENERIC 0u",
        "#define E1ENV_PLANE_X_POS 1u",
        "#define E1ENV_PLANE_X_NEG 2u",
        "#define E1ENV_PLANE_Y_POS 3u",
        "#define E1ENV_PLANE_Y_NEG 4u",
        "#define E1ENV_PLANE_XPYP 5u",
        "#define E1ENV_PLANE_XPYN 6u",
        "#define E1ENV_PLANE_XNYP 7u",
        "#define E1ENV_PLANE_XNYN 8u",
        emit("uint8_t","k_e1env_plane_op",ops),
        emit("int16_t","k_e1env_plane_c",const),
        "#endif",
        "",
    ]
    out=pathlib.Path(a.out); out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text("\n\n".join(hdr))
    canonical=sum(counts[i] for i in range(1,9))
    cardinal=sum(counts[i] for i in range(1,5))
    diagonal=sum(counts[i] for i in range(5,9))
    print(f"E1ENV_PLANE_META surfaces={len(ops)} canonical={canonical} cardinal={cardinal} diagonal45={diagonal} generic={counts[0]}")
    print("plane_ops="+",".join(map(str,ops)))

if __name__=="__main__":
    main()
