#!/usr/bin/env python3
"""Generate exact ROM endpoint-depth evaluators for the Q4 envelope renderer.

Runtime inv_at_invd() currently recomputes wall-normal dot products, trigonometry
lookups, secant correction and four generic multiplies for every visible run.
For exact-envelope runs the sample rays are always one of the 21 baked coarse
column edges.  That makes the expensive angular part a finite ROM vocabulary.

For each unique wall-normal class, yaw and coarse edge this generator stores the
EXACT abs(dot) byte used by inv_at_invd().  sec(rel) is only 21 bytes. Runtime
then reproduces the same two rounded products with an exact quarter-square
uint8 multiply, so endpoint inverse depths stay bit-identical to the existing
path while the Z80 trades arithmetic for ROM reads.

Orthogonal-only geometry has only +/-X and +/-Y normals. Endpoint projection
uses abs(dot), so normal sign is irrelevant. Generate one +X bank and one +Y
bank: four directed normals collapse to two axis vocabularies without adding a
runtime yaw-phase transform to the hot envelope emitter.
"""
from __future__ import annotations
import argparse
import pathlib
import re

EDGES=(-512,-479,-442,-400,-355,-305,-251,-193,-132,-69,-4,
        61,125,187,245,299,350,396,438,476,506)

def arr(text,name):
    m=re.search(r"static\s+const\s+[^;=]+?\b"+re.escape(name)+r"\s*\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not m:
        raise SystemExit("missing generated array "+name)
    return [int(x,0) for x in re.findall(r"-?0x[0-9A-Fa-f]+|-?\d+",m.group(1))]

def shr0(v,n):
    return v>>n if v>=0 else -((-v)>>n)

def emit_u8(name,data,per=21):
    out=[f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def emit_u16(name,data,per=12):
    out=[f"static const uint16_t {name}[{len(data)}] = {{"]
    for i in range(0,len(data),per):
        out.append("    "+", ".join(str(v) for v in data[i:i+per])+",")
    out.append("};")
    return "\n".join(out)

def dot_for(nx,ny,yaw,rel,sin):
    wb=((yaw<<4)+rel)&4095
    bi=(wb>>4)&255
    sn=sin[bi]
    cs=sin[(bi+64)&255]
    if ny==0 and (nx==32 or nx==-32):
        dot=cs
    elif nx==0 and (ny==32 or ny==-32):
        dot=sn
    else:
        dot=shr0(nx*cs+ny*sn,5)
    dot=abs(dot)
    return min(127,dot)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--map-inc",required=True)
    ap.add_argument("--out-dir",required=True)
    ap.add_argument("--bank-base",type=int,default=236)
    args=ap.parse_args()

    text=pathlib.Path(args.map_inc).read_text()
    nx=arr(text,"k_tspf_nx_q5")
    ny=arr(text,"k_tspf_ny_q5")
    sin=arr(text,"k_tspf_sin_q7")
    sec=arr(text,"k_tspf_sec_q7")
    invz=arr(text,"k_tspf_invz")
    source_normals=[]
    axis=[]
    for qx,qy in zip(nx,ny):
        p=(qx,qy)
        if p not in source_normals: source_normals.append(p)
        if qy==0 and (qx==32 or qx==-32):
            axis.append(0)  # X; sign folds under abs(dot)
        elif qx==0 and (qy==32 or qy==-32):
            axis.append(1)  # Y
        else:
            raise SystemExit(f"ORTHOGONAL_DEPTH_REQUIRED normal={p}")
    canonical_normals=((32,0),(0,32))

    edge_sec=[sec[abs(r)] for r in EDGES]
    # Exact replacement for round(q * sec(edge) / 128), including saturation.
    # With one normal class per bank this 5.25 KiB table fits in the space
    # reclaimed from the second class's dot field and removes two Z80 multiplies
    # per visible run.
    sec_eval=[]
    for s in edge_sec:
        for q in range(256):
            v=(q*s+64)>>7
            sec_eval.append(255 if v>255 else v)
    col_recip=[0,255,128,85,64,51,43,36,32,28,26,23,21,20,18,17,16,15,14,13,13]

    # Exact replacement for renderer inv_for_dq4() over its complete useful
    # absolute-distance domain.  ROM is deliberately plentiful in this build:
    # spend ~2 KiB per depth bank to remove interpolation arithmetic from every
    # visible FULL span without introducing another bank switch.
    def inv_for_abs_q4(a):
        if a <= (10 << 4):
            return 255
        if a >= (127 << 4):
            return invz[127]
        z=a >> 4
        f=a & 15
        x0=invz[z]
        x1=invz[z+1]
        d=x1-x0
        return x0 + shr0(d*f + (8 if d >= 0 else -8), 4)
    invd_q4=[inv_for_abs_q4(a) for a in range((127 << 4)+1)]

    outdir=pathlib.Path(args.out_dir); outdir.mkdir(parents=True,exist_ok=True)
    hdr=[
        "/* GENERATED by tools/e1env_depth_edges_bank.py. */",
        "#ifndef E1ENV_DEPTH_EDGES_BANK_H",
        "#define E1ENV_DEPTH_EDGES_BANK_H",
        "#include <stdint.h>",
        "#include <gbdk/platform.h>",
        "#define E1ENV_DEPTH_EDGES_BANK 1u",
        "#define E1ENV_DEPTH_ORTHOGONAL_AXES 1u",
        emit_u8("k_e1env_depth_axis",axis,20),
        "extern int16_t g_e1env_depth_iq;",
        "extern int16_t g_e1env_depth_step;",
        "extern uint8_t g_e1env_depth_start_half;",
        "extern uint8_t g_e1env_depth_end_half;",
    ]

    bank_count=2
    for bi in range(bank_count):
        hdr.append(f"void e1env_depth_edges_{bi}(uint8_t yaw,uint8_t c0,uint8_t c1,int16_t dq4) BANKED;")
    hdr += ["#endif",""]
    (outdir/"e1env_depth_edges_bank.h").write_text("\n".join(hdr))

    for bank_i in range(bank_count):
        cx,cy=canonical_normals[bank_i]
        dots=[]
        for yaw in range(256):
            for rel in EDGES:
                dots.append(dot_for(cx,cy,yaw,rel,sin))

        fn=f"e1env_depth_edges_{bank_i}"
        bridge_defs=("int16_t g_e1env_depth_iq;\n"
                     "int16_t g_e1env_depth_step;\n"
                     "uint8_t g_e1env_depth_start_half;\n"
                     "uint8_t g_e1env_depth_end_half;") if bank_i==0 else (
                     "extern int16_t g_e1env_depth_iq;\n"
                     "extern int16_t g_e1env_depth_step;\n"
                     "extern uint8_t g_e1env_depth_start_half;\n"
                     "extern uint8_t g_e1env_depth_end_half;")
        src=f"""/* GENERATED by tools/e1env_depth_edges_bank.py. */
#include <stdint.h>
#include <gbdk/platform.h>
#pragma bank {args.bank_base+bank_i}
BANKREF(e1env_depth_edges_{bank_i})

{emit_u8("k_dot",dots,21)}

{emit_u8("k_sec_eval",sec_eval,32)}

{emit_u8("k_invd_q4",invd_q4,32)}

{emit_u8("k_col_recip_q8",col_recip,21)}

{bridge_defs}

extern uint16_t e1env_mul8u(uint8_t a,uint8_t b);
static uint8_t eval_one(uint8_t dot,uint8_t edge,uint8_t invd) {{
    uint16_t p=e1env_mul8u(invd,dot);
    uint8_t q=(uint8_t)((p+64u)>>7);
    return k_sec_eval[((uint16_t)edge<<8)|q];
}}

void {fn}(uint8_t yaw,uint8_t c0,uint8_t c1,int16_t dq4) BANKED {{
    uint16_t ad=(uint16_t)(dq4<0 ? -dq4 : dq4);
    uint16_t base=(uint16_t)yaw*21u;
    uint8_t invd=k_invd_q4[ad>=2032u ? 2032u : ad];
    uint8_t a=eval_one(k_dot[base+c0],c0,invd);
    uint8_t e=(uint8_t)(c1+1u);
    uint8_t b=eval_one(k_dot[base+e],e,invd);
    {{
        uint8_t n=(uint8_t)(c1-c0+1u);
        int16_t d=(int16_t)b-(int16_t)a;
        uint8_t mag=(uint8_t)(d<0 ? -d : d);
        uint16_t p=e1env_mul8u(mag,k_col_recip_q8[n]);
        int16_t st=(int16_t)(p>>2);
        g_e1env_depth_iq=(int16_t)((uint16_t)a<<6);
        g_e1env_depth_step=d<0 ? (int16_t)-st : st;
    }}
    return;
}}
"""
        (outdir/f"{fn}.c").write_text(src)

    data_bytes=bank_count*(256*21 + len(sec_eval) + len(invd_q4) + len(col_recip))
    print(f"E1ENV_DEPTH_EDGES banks={bank_count} bank_range={args.bank_base}..{args.bank_base+bank_count-1} "
          f"source_normal_classes={len(source_normals)} canonical_classes=2 approx_data_bytes={data_bytes}")

if __name__=="__main__":
    main()
