#!/usr/bin/env python3
"""Emit deliberately-uncompressed banked E1M1 front-envelope records.

One 0.5-world-unit spatial row becomes one BANKED object. Every cell has a
fixed-size record:
  byte 0      span count, or 0xff = use legacy PVS fallback
  bytes 1..   (boundary_vertex, first_hit_surface) pairs, padded with 0xff

This intentionally spends ROM to make the Z80 lookup stupid: select row bank,
copy one fixed record, consume it. No dictionary decode and no compression.
"""
from __future__ import annotations
import argparse
from pathlib import Path
import e1m1_latest_full_bake as base
import e1m1_front_envelope_bake as env

CELL=0.5

def c_row_array(name, rows, cols=18):
    flat=[b for rec in rows for b in rec]
    out=[f"static const uint8_t {name}[{len(flat)}] = {{"]
    for i in range(0,len(flat),cols):
        out.append("    "+", ".join(str(x) for x in flat[i:i+cols])+",")
    out.append("};")
    return "\n".join(out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--geometry",default="src/generated/e1m1_room1_exact_geometry.h")
    ap.add_argument("--floor",default="src/generated/e1m1_room1_exact_floor.h")
    ap.add_argument("--out-dir",required=True)
    args=ap.parse_args()

    verts0,segs0=base.parse_geometry(Path(args.geometry))
    offs,runs=base.parse_floor(Path(args.floor))
    verts,segs,_=base.flatten_compact(verts0,segs0,())
    result=env.bake(CELL,verts,segs,offs,runs)
    max_spans=max((len(p) for p in result["programs"]),default=0)
    record_bytes=1+2*max_spans
    out=Path(args.out_dir); out.mkdir(parents=True,exist_ok=True)

    hdr=[
      "/* GENERATED by e1m1_front_envelope_bankgen.py. */",
      "#ifndef E1M1_FRONT_ENVELOPE_META_H",
      "#define E1M1_FRONT_ENVELOPE_META_H",
      "#include <stdint.h>",
      "#include <gbdk/platform.h>",
      f"#define E1ENV_WORLD_MIN_X_Q4 {base.WORLD_MIN_X<<4}",
      f"#define E1ENV_WORLD_MIN_Y_Q4 {base.WORLD_MIN_Y<<4}",
      "#define E1ENV_CELL_SHIFT 3u",
      f"#define E1ENV_COLS {result['cols']}u",
      f"#define E1ENV_ROWS {result['rows']}u",
      f"#define E1ENV_MAX_SPANS {max_spans}u",
      f"#define E1ENV_RECORD_BYTES {record_bytes}u",
      "#define E1ENV_FALLBACK 255u",
    ]
    dispatch=[]
    stable=0
    for gy in range(result["rows"]):
        records=[]
        for gx in range(result["cols"]):
            pid=result["grid"][gy*result["cols"]+gx]
            if pid==env.FALLBACK:
                rec=[255]+[255]*(record_bytes-1)
            else:
                p=result["programs"][pid]
                rec=[len(p)]
                for v,sid in p:
                    rec += [v,sid]
                rec += [255]*(record_bytes-len(rec))
                stable += 1
            records.append(rec)
        src=f"""/* GENERATED front-envelope row {gy}. */
#include <stdint.h>
#include <string.h>
#include <gbdk/platform.h>
#pragma bank 255
BANKREF(e1env_row{gy})

{c_row_array("k_e1env_row",records)}

void tsp_e1env_load_row{gy}(uint8_t gx, uint8_t *dst) BANKED {{
    uint16_t off=(uint16_t)gx*E1ENV_RECORD_BYTES;
    memcpy(dst,&k_e1env_row[off],E1ENV_RECORD_BYTES);
}}
"""
        # Each C file includes meta for record size, but keeps its payload local
        src=src.replace("#include <gbdk/platform.h>","#include <gbdk/platform.h>\n#include \"e1m1_front_envelope_meta.h\"")
        (out/f"e1env_row{gy}.c").write_text(src)
        hdr.append(f"void tsp_e1env_load_row{gy}(uint8_t gx, uint8_t *dst) BANKED;")
        dispatch.append(f"case {gy}u: tsp_e1env_load_row{gy}(gx,dst); break;")

    hdr.append("#endif")
    (out/"e1m1_front_envelope_meta.h").write_text("\n".join(hdr)+"\n")
    (out/"e1m1_front_envelope_dispatch.inc").write_text("\n".join(dispatch)+"\n")

    per_row=result["cols"]*record_bytes
    total=result["rows"]*per_row
    print(f"E1ENV_BANKGEN_PASS cell={CELL:g} rows={result['rows']} cols={result['cols']} "
          f"max_spans={max_spans} record_bytes={record_bytes}")
    print(f"fixed_rom_payload_bytes={total} bytes_per_row_bank={per_row} row_banks={result['rows']}")
    print(f"stable_records={stable} fallback_records={result['rows']*result['cols']-stable}")
    if per_row>=15000:
        raise SystemExit("row payload too large for comfortable 16 KiB bank")

if __name__=="__main__":
    main()
