#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "e1m1_room1_world.h"
#include "tilesector_polar.h"
#include "generated/e1m1_room1_exact_floor.h"
#include "e1m1_room1_polar_meta.h"

#define WMINX E1X_WORLD_MIN_X
#define WMINY E1X_WORLD_MIN_Y
#define WMAXX E1X_WORLD_MAX_X
#define WMAXY E1X_WORLD_MAX_Y
#define CELL 8
#define COLS ((WMAXX-WMINX)/CELL)
#define ROWS ((WMAXY-WMINY)/CELL)
#define YAW_BINS 16
#define MASK_BYTES 8

extern uint8_t g_tspf_e1_host_all_segments;
extern uint8_t g_e1_host_owner_bits[8];

static void to_polar(int16_t xq,int16_t yq,uint8_t yaw,TSPState *p){
    memset(p,0,sizeof(*p));
    p->x_q4=xq;
    p->y_q4=yq;
    p->z_q4=(int16_t)(E1_EYE_HEIGHT_Q4+e1_room1_floor_z_q4(xq,yq));
    p->yaw=yaw;
    p->speed_scale=1u;
}

static unsigned pop8(uint8_t v){
    unsigned n=0u;
    while(v){v=(uint8_t)(v&(uint8_t)(v-1u));++n;}
    return n;
}

static void emit_header(FILE *f){
    fputs("/* GENERATED by tools/e1m1_owner_pvs_gen.c. */\n",f);
    fputs("#ifndef E1M1_ROOM1_POLAR_PVS_H\n#define E1M1_ROOM1_POLAR_PVS_H\n",f);
    fputs("#include <stdint.h>\n",f);
    fputs("#if defined(__SDCC)\n#include <gbdk/platform.h>\n#else\n#ifndef BANKED\n#define BANKED\n#endif\n#endif\n",f);
    fprintf(f,"#define E1PF_PVS_COLS %uu\n#define E1PF_PVS_ROWS %uu\n",COLS,ROWS);
    fprintf(f,"#define E1PF_PVS_YAW_BINS %uu\n#define E1PF_PVS_MASK_BYTES %uu\n",YAW_BINS,MASK_BYTES);
    fputs("void e1pf_load_pvs(uint8_t gx,uint8_t gy,uint8_t yaw_bin,uint8_t out[8]) BANKED;\n",f);
    fputs("#endif\n",f);
}

static void emit_source(FILE *f,const uint8_t *masks){
    unsigned i,total=(unsigned)(COLS*ROWS*YAW_BINS*MASK_BYTES);
    fputs("/* GENERATED by tools/e1m1_owner_pvs_gen.c. */\n",f);
    fputs("#include <stdint.h>\n",f);
    fputs("#if defined(__SDCC)\n#include <gbdk/platform.h>\n#pragma bank 20\nBANKREF(e1m1_room1_polar_pvs_bank)\n#endif\n",f);
    fputs("#include \"e1m1_room1_polar_pvs.h\"\n",f);
    fprintf(f,"static const uint8_t k_e1pf_pvs[%u] = {\n",total);
    for(i=0u;i<total;++i){
        if((i%24u)==0u)fputs("    ",f);
        fprintf(f,"%u,",(unsigned)masks[i]);
        if((i%24u)==23u||i+1u==total)fputc('\n',f);
    }
    fputs("};\n\n",f);
    fputs("void e1pf_load_pvs(uint8_t gx,uint8_t gy,uint8_t yaw_bin,uint8_t out[8]) BANKED {\n",f);
    fputs("    uint8_t i; uint16_t cell,off;\n",f);
    fputs("    if(gx>=E1PF_PVS_COLS||gy>=E1PF_PVS_ROWS){for(i=0u;i<8u;++i)out[i]=0u;return;}\n",f);
    fputs("    cell=(uint16_t)((uint16_t)gy*E1PF_PVS_COLS+gx);\n",f);
    fputs("    off=(uint16_t)((cell<<7)+((uint16_t)(yaw_bin&15u)<<3));\n",f);
    fputs("    for(i=0u;i<8u;++i)out[i]=k_e1pf_pvs[off+i];\n",f);
    fputs("}\n",f);
}

int main(int argc,char **argv){
    uint8_t *masks;
    unsigned gx,gy,yb,bi;
    unsigned long count_sum=0u;
    unsigned count_min=999u,count_max=0u;
    unsigned spawn_count=0u;
    FILE *hf,*sf;
    TSPState p;
    uint16_t map[TSP_MAP_CELLS];

    if(argc!=3){
        fprintf(stderr,"usage: %s OUT_HEADER OUT_SOURCE\n",argv[0]);
        return 2;
    }

    masks=(uint8_t *)calloc((size_t)COLS*ROWS*YAW_BINS*MASK_BYTES,1u);
    if(!masks){fprintf(stderr,"allocation failed\n");return 2;}

    g_tspf_appearance_mode=0u;
    g_tspf_e1_host_all_segments=1u;

    for(gy=0u;gy<ROWS;++gy){
        for(gx=0u;gx<COLS;++gx){
            const int x0=WMINX+(int)gx*CELL;
            const int y0=WMINY+(int)gy*CELL;
            for(yb=0u;yb<YAW_BINS;++yb){
                uint8_t owner_union[8]={0,0,0,0,0,0,0,0};
                unsigned sx,sy,yi;
                static const int8_t yaw_off[5]={-8,-4,0,4,7};

                /* Half-world-unit lattice.  This is deliberately denser than
                 * the runtime movement grid used by the dense CI control and
                 * includes every integer-world sample in that control. */
                for(sy=0u;sy<16u;++sy){
                    int16_t yq=(int16_t)((y0<<4)+(int)sy*8+4);
                    for(sx=0u;sx<16u;++sx){
                        int16_t xq=(int16_t)((x0<<4)+(int)sx*8+4);
                        if(!e1_room1_is_walkable_q4(xq,yq))continue;
                        for(yi=0u;yi<5u;++yi){
                            uint8_t yaw=(uint8_t)((int)(yb*16u)+yaw_off[yi]);
                            to_polar(xq,yq,yaw,&p);
                            tsp_polar_renderer_reset();
                            tsp_polar_render(&p,map,(TSPColumn *)0);
                            for(bi=0u;bi<8u;++bi)owner_union[bi]|=g_e1_host_owner_bits[bi];
                        }
                    }
                }

                /* Also sample the exact cell boundaries at integer-world
                 * positions.  Visibility ownership changes on these lines,
                 * and movement/collision can place the eye precisely there. */
                for(sy=0u;sy<=8u;++sy){
                    int16_t yq=(int16_t)((y0+(int)sy)<<4);
                    for(sx=0u;sx<=8u;++sx){
                        int16_t xq=(int16_t)((x0+(int)sx)<<4);
                        if(!e1_room1_is_walkable_q4(xq,yq))continue;
                        for(yi=0u;yi<5u;++yi){
                            uint8_t yaw=(uint8_t)((int)(yb*16u)+yaw_off[yi]);
                            to_polar(xq,yq,yaw,&p);
                            tsp_polar_renderer_reset();
                            tsp_polar_render(&p,map,(TSPColumn *)0);
                            for(bi=0u;bi<8u;++bi)owner_union[bi]|=g_e1_host_owner_bits[bi];
                        }
                    }
                }

                {
                    unsigned off=(((gy*COLS+gx)*YAW_BINS+yb)*MASK_BYTES);
                    unsigned pc=0u;
                    for(bi=0u;bi<8u;++bi){masks[off+bi]=owner_union[bi];pc+=pop8(owner_union[bi]);}
                    count_sum+=pc;
                    if(pc<count_min)count_min=pc;
                    if(pc>count_max)count_max=pc;
                    if(gx==0u&&gy==3u&&yb==0u)spawn_count=pc;
                }
            }
        }
    }

    g_tspf_e1_host_all_segments=0u;

    hf=fopen(argv[1],"wb");
    if(!hf){perror(argv[1]);free(masks);return 2;}
    emit_header(hf);fclose(hf);
    sf=fopen(argv[2],"wb");
    if(!sf){perror(argv[2]);free(masks);return 2;}
    emit_source(sf,masks);fclose(sf);

    printf("E1PF_OWNER_BAKE_PASS cells=%u yaw_bins=%u masks=%u\n",
           (unsigned)(COLS*ROWS),YAW_BINS,(unsigned)(COLS*ROWS*YAW_BINS));
    printf("candidate_count mean=%.2f min=%u max=%u\n",
           (double)count_sum/(double)(COLS*ROWS*YAW_BINS),count_min,count_max);
    printf("spawn_candidate_count=%u\n",spawn_count);
    printf("pvs_bytes=%u sample_step_q4=8 yaw_samples=5\n",
           (unsigned)(COLS*ROWS*YAW_BINS*MASK_BYTES));

    free(masks);
    return 0;
}
