#!/usr/bin/env python3
"""Generate the mature Polar 4bpp tile vocabulary for E1M1 at build time.

The original demo synthesized 423 tiles pixel-by-pixel on the Z80 before
entering gameplay.  That is useful as a tiny reference generator but a poor
production startup path.  This tool emits the byte-identical planar tile set
offline, plus one banked bulk uploader.
"""
from __future__ import annotations

import argparse
from pathlib import Path

TSP_SHADE_COUNT=3
TSP_BORDER_COUNT=4
TSP_CAP_COUNT=3
TSP_EDGE_OFF_MIN=-7
TSP_EDGE_OFF_COUNT=16
TSP_EDGE_SLOPE_COUNT=8

TSP_TILE_CEILING=0
TSP_TILE_FLOOR=1
TSP_TILE_HORIZON=2
TSP_TILE_FULL_BASE=3
TSP_TILE_EDGE_BASE=TSP_TILE_FULL_BASE+TSP_SHADE_COUNT*TSP_CAP_COUNT*TSP_BORDER_COUNT
TSP_GENERATED_TILE_COUNT=TSP_TILE_EDGE_BASE+TSP_SHADE_COUNT*TSP_EDGE_OFF_COUNT*TSP_EDGE_SLOPE_COUNT

TSP_CAP_NONE=0
TSP_CAP_TOP=1
TSP_CAP_BOTTOM=2

C_BLACK=0
C_OUT=1
C_FLOOR=2
C_FAR=3
C_MID=4
C_NEAR=5

EDGE_LUT=(
    (0,0,0,0,0,0,0,0),
    (0,0,0,0,1,1,1,1),
    (0,0,1,1,1,1,2,2),
    (0,0,1,1,2,2,3,3),
    (0,1,1,2,2,3,3,4),
    (0,1,1,2,3,4,4,5),
    (0,1,2,3,3,4,5,6),
    (0,1,2,3,4,5,6,7),
)

def full_id(shade:int,cap:int,border:int)->int:
    return TSP_TILE_FULL_BASE+(((shade*TSP_CAP_COUNT)+cap)*TSP_BORDER_COUNT)+border

def edge_id(shade:int,oi:int,si:int)->int:
    return TSP_TILE_EDGE_BASE+(((shade*TSP_EDGE_OFF_COUNT)+oi)*TSP_EDGE_SLOPE_COUNT)+si

def shade_color(shade:int)->int:
    return C_FAR if shade==0 else (C_MID if shade==1 else C_NEAR)

def encode_tile(pixels:list[list[int]])->bytes:
    out=bytearray()
    for y in range(8):
        row=pixels[y]
        planes=[0,0,0,0]
        for x,color in enumerate(row):
            bit=0x80>>x
            for plane in range(4):
                if color & (1<<plane):
                    planes[plane] |= bit
        out.extend(planes)
    assert len(out)==32
    return bytes(out)

def solid(color:int)->bytes:
    return encode_tile([[color]*8 for _ in range(8)])

def horizon()->bytes:
    return encode_tile([[C_BLACK if y==0 else C_FLOOR for _x in range(8)] for y in range(8)])

def full(shade:int,cap:int,border:int)->bytes:
    color=shade_color(shade)
    px=[]
    for y in range(8):
        row=[]
        for x in range(8):
            black=((border&1) and x==0) or ((border&2) and x==7)
            if cap==TSP_CAP_TOP and y==0:
                black=True
            if cap==TSP_CAP_BOTTOM and y==7:
                black=True
            row.append(C_BLACK if black else color)
        px.append(row)
    return encode_tile(px)

def edge(shade:int,oi:int,si:int)->bytes:
    color=shade_color(shade)
    off=TSP_EDGE_OFF_MIN+oi
    px=[]
    for y in range(8):
        row=[]
        for x in range(8):
            line=off+EDGE_LUT[si][x]
            row.append(C_OUT if y<line else (C_BLACK if y==line else color))
        px.append(row)
    return encode_tile(px)

def build()->bytes:
    tiles=[bytes(32) for _ in range(TSP_GENERATED_TILE_COUNT)]
    tiles[TSP_TILE_CEILING]=solid(C_OUT)
    tiles[TSP_TILE_FLOOR]=solid(C_FLOOR)
    tiles[TSP_TILE_HORIZON]=horizon()
    for s in range(TSP_SHADE_COUNT):
        for cap in range(TSP_CAP_COUNT):
            for border in range(TSP_BORDER_COUNT):
                tiles[full_id(s,cap,border)]=full(s,cap,border)
    for s in range(TSP_SHADE_COUNT):
        for oi in range(TSP_EDGE_OFF_COUNT):
            for si in range(TSP_EDGE_SLOPE_COUNT):
                tiles[edge_id(s,oi,si)]=edge(s,oi,si)
    blob=b"".join(tiles)
    assert len(blob)==TSP_GENERATED_TILE_COUNT*32
    return blob

def emit(out_dir:Path,bank:int)->None:
    blob=build()
    out_dir.mkdir(parents=True,exist_ok=True)
    h=out_dir/"e1m1_room1_polar_tiles.h"
    c=out_dir/"e1m1_room1_polar_tiles.c"

    h.write_text(
        "/* GENERATED by tools/e1m1_room1_polar_tiles_gen.py. */\n"
        "#ifndef E1M1_ROOM1_POLAR_TILES_H\n#define E1M1_ROOM1_POLAR_TILES_H\n"
        "#if defined(__SDCC)\n#include <gbdk/platform.h>\n"
        "#else\n#ifndef BANKED\n#define BANKED\n#endif\n#endif\n"
        "void e1m1_room1_polar_tiles_init(void) BANKED;\n"
        "#endif\n"
    )

    lines=[]
    for i in range(0,len(blob),24):
        lines.append("    "+",".join(f"0x{x:02x}" for x in blob[i:i+24])+",")
    c.write_text(
        "/* GENERATED by tools/e1m1_room1_polar_tiles_gen.py. */\n"
        "#include <stdint.h>\n"
        "#include <gbdk/platform.h>\n"
        '#include "tilesector_polar.h"\n'
        '#include "e1m1_room1_polar_tiles.h"\n'
        f"#if defined(__SDCC)\n#pragma bank {bank}\nBANKREF(e1m1_room1_polar_tiles_bank)\n#endif\n"
        f"static const uint8_t k_e1pf_tiles[{len(blob)}] = {{\n"+
        "\n".join(lines)+
        "\n};\n"
        "void e1m1_room1_polar_tiles_init(void) BANKED {\n"
        "    set_bkg_4bpp_data(0u,TSP_GENERATED_TILE_COUNT,k_e1pf_tiles);\n"
        "}\n"
    )
    print(f"E1PF_TILES_PASS tiles={TSP_GENERATED_TILE_COUNT} bytes={len(blob)} bank={bank}")
    print(f"vram_tile_end=0x{len(blob):04x} name_table_base=0x3800 margin={0x3800-len(blob)}")

def main()->None:
    ap=argparse.ArgumentParser()
    ap.add_argument("--out-dir",required=True)
    ap.add_argument("--bank",type=int,default=18)
    args=ap.parse_args()
    if not 1<=args.bank<=254:
        raise SystemExit("bank must be 1..254")
    emit(Path(args.out_dir),args.bank)

if __name__=="__main__":
    main()
