#!/usr/bin/env python3
"""Generate a conservative spatial/yaw PVS for exact E1M1 Room 1.

The output is deliberately a candidate mask, not a final visibility answer.
Runtime projection/depth still decides what actually draws. False positives cost
cycles; false negatives are prevented with a generously inflated angular cone,
multiple camera samples inside each 8x8 cell, and an unconditional near-wall
rule.
"""
from __future__ import annotations
import argparse
import math
import re
from pathlib import Path

WORLD_MIN_X=16
WORLD_MIN_Y=24
WORLD_MAX_X=112
WORLD_MAX_Y=80
CELL=8
COLS=(WORLD_MAX_X-WORLD_MIN_X)//CELL
ROWS=(WORLD_MAX_Y-WORLD_MIN_Y)//CELL
YAW_BINS=16
MASK_BYTES=8
HALF_CONE_DEG=70.0
NEAR_ALWAYS=8.0

def parse_geometry(path: Path):
    text=path.read_text()
    vm=re.search(r"k_e1x_vertices\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    sm=re.search(r"k_e1x_segments\[[^\]]+\]\s*=\s*\{(.*?)\};",text,re.S)
    if not vm or not sm:
        raise SystemExit("could not parse exact geometry header")
    verts=[tuple(map(int,m)) for m in re.findall(r"\{\s*(\d+)\s*,\s*(\d+)\s*\}",vm.group(1))]
    segs=[]
    for m in re.finditer(
        r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*\}",
        sm.group(1)):
        a,b,z0,z1,occ,bias=map(int,m.groups())
        segs.append((a,b,z0,z1,occ,bias))
    if len(verts)!=44 or len(segs)!=58:
        raise SystemExit(f"unexpected geometry: verts={len(verts)} segs={len(segs)}")
    return verts,segs

def angle_diff(a,b):
    return abs((a-b+math.pi)%(2.0*math.pi)-math.pi)

def point_segment_dist(px,py,ax,ay,bx,by):
    vx,vy=bx-ax,by-ay
    vv=vx*vx+vy*vy
    if vv<=1e-12:
        return math.hypot(px-ax,py-ay)
    t=((px-ax)*vx+(py-ay)*vy)/vv
    t=max(0.0,min(1.0,t))
    return math.hypot(px-(ax+t*vx),py-(ay+t*vy))

def candidate_for_cell_yaw(verts,segs,gx,gy,yaw):
    x0=WORLD_MIN_X+gx*CELL
    y0=WORLD_MIN_Y+gy*CELL
    cameras=[
        (x0+4.0,y0+4.0),
        (x0+0.5,y0+0.5),(x0+7.5,y0+0.5),
        (x0+0.5,y0+7.5),(x0+7.5,y0+7.5),
    ]
    half=math.radians(HALF_CONE_DEG)
    mask=0
    for sid,(a,b,_z0,_z1,_occ,_bias) in enumerate(segs):
        ax,ay=verts[a]; bx,by=verts[b]
        samples=[
            (ax,ay),(bx,by),
            ((ax+bx)*0.5,(ay+by)*0.5),
            ((3*ax+bx)*0.25,(3*ay+by)*0.25),
            ((ax+3*bx)*0.25,(ay+3*by)*0.25),
        ]
        keep=False
        for px,py in cameras:
            if point_segment_dist(px,py,ax,ay,bx,by)<=NEAR_ALWAYS:
                keep=True
                break
            for sx,sy in samples:
                if angle_diff(math.atan2(sy-py,sx-px),yaw)<=half:
                    keep=True
                    break
            if keep:
                break
        if keep:
            mask|=1<<sid
    return mask

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--geometry",default="src/generated/e1m1_room1_exact_geometry.h")
    ap.add_argument("--out",required=True)
    args=ap.parse_args()
    verts,segs=parse_geometry(Path(args.geometry))
    masks=[]
    counts=[]
    for gy in range(ROWS):
        for gx in range(COLS):
            for yb in range(YAW_BINS):
                yaw=2.0*math.pi*yb/YAW_BINS
                mask=candidate_for_cell_yaw(verts,segs,gx,gy,yaw)
                masks.append(mask)
                counts.append(mask.bit_count())

    out=Path(args.out)
    out.parent.mkdir(parents=True,exist_ok=True)
    with out.open("w") as f:
        f.write("/* GENERATED by tools/e1m1_room1_pvs_gen.py. */\n")
        f.write("#ifndef E1M1_ROOM1_PVS_H\n#define E1M1_ROOM1_PVS_H\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define E1X_PVS_CELL_COLS {COLS}u\n")
        f.write(f"#define E1X_PVS_CELL_ROWS {ROWS}u\n")
        f.write(f"#define E1X_PVS_YAW_BINS {YAW_BINS}u\n")
        f.write(f"#define E1X_PVS_MASK_BYTES {MASK_BYTES}u\n")
        f.write(f"static const uint8_t k_e1x_pvs[{len(masks)*MASK_BYTES}] = {{\n")
        flat=[]
        for m in masks:
            flat.extend((m>>(8*i))&255 for i in range(MASK_BYTES))
        for i in range(0,len(flat),24):
            f.write("    "+",".join(str(v) for v in flat[i:i+24])+",\n")
        f.write("};\n#endif\n")

    print(f"PVS_GENERATED cells={COLS*ROWS} yaw_bins={YAW_BINS} masks={len(masks)}")
    print(f"candidate_count mean={sum(counts)/len(counts):.2f} min={min(counts)} max={max(counts)}")
    print(f"bytes={len(masks)*MASK_BYTES} half_cone_deg={HALF_CONE_DEG:g} near_always={NEAR_ALWAYS:g}")

if __name__=="__main__":
    main()
