/*
 * Dump the edge_entry lookup table, generated BY the shipped edge_entry rather
 * than by a reimplementation of it, so the table cannot drift from the
 * renderer's semantics.
 *
 * Layout, chosen so the row base hoists out of the per-row loop: `bottom` and
 * `slope` are fixed for a whole draw_edge call and only local_left varies, so
 * the row is (bottom*15 + slope+7) and the entry index within it is
 * local_left+8. Rows are padded to 64 bytes so the row base is a shift.
 *
 *   row   = bottom*15 + (slope+7)        0..29
 *   entry = local_left + 8               0..23   (local_left clamped to -8..15)
 *   addr  = LUT + row*64 + entry*2
 *
 * The clamp window [-8,15] is not a guess: verified exhaustively over
 * local_left in [-400,400] with 0 mismatches, because `off` saturates outside
 * it for every slope and both bottoms.
 *
 * The stored value is the word MINUS the shade-dependent EDGEBASE, so one
 * table serves all three shades: the kernel already holds EDGEBASE at 0xc02a.
 */
#include <stdio.h>
#include "tilesector_polar_renderer.c"

#define ROWS 30
#define COLS 24
#define STRIDE 32           /* entries per row, padded; 64 bytes */

int main(void)
{
    int bot, sl, ll, base0 = TSP_TILE_EDGE_BASE;
    unsigned bad = 0;
    printf("# edge_entry LUT: %d rows x %d bytes = %d bytes\n",
           ROWS, STRIDE * 2, ROWS * STRIDE * 2);
    for (bot = 0; bot < 2; ++bot)
      for (sl = -7; sl <= 7; ++sl) {
          int row = bot * 15 + (sl + 7);
          printf("ROW %d", row);
          for (ll = -8; ll <= 15; ++ll) {
              uint16_t w = edge_entry(0u, (int16_t)ll, (int8_t)sl, (uint8_t)bot);
              int v = (int)w - base0;
              /* the same entry must serve every shade */
              if (edge_entry(1u, (int16_t)ll, (int8_t)sl, (uint8_t)bot)
                    != (uint16_t)(v + base0 + 1 * TSP_EDGE_OFF_COUNT
                                          * TSP_EDGE_SLOPE_COUNT)) ++bad;
              if (edge_entry(2u, (int16_t)ll, (int8_t)sl, (uint8_t)bot)
                    != (uint16_t)(v + base0 + 2 * TSP_EDGE_OFF_COUNT
                                          * TSP_EDGE_SLOPE_COUNT)) ++bad;
              if (v < 0 || v > 0xffff) ++bad;
              printf(" %d", v);
          }
          for (ll = COLS; ll < STRIDE; ++ll) printf(" 0");
          printf("\n");
      }
    fprintf(stderr, "shade-independence violations: %u\n", bad);
    return bad ? 1 : 0;
}
