#!/usr/bin/env python3
"""EDGELUT: replace edge_entry's arithmetic with a table read. A/B against DDA_G.

A37's census established that `edge_entry` is not a rasterizer - it selects from
a baked vocabulary of 423 tiles, and its output is a pure function of
(shade, local_left, slope, bottom). Profiled, that selection is **19.6% of
DDA_G** (38,806 T of 197,919 per pose).

THE STRUCTURAL POINT, which is what makes this worth doing
---------------------------------------------------------
A naive table still has to build an index from three values per row, which is
about as expensive as the arithmetic it replaces. But `bottom` and `slope` are
constant for a whole `draw_edge` call and only `local_left` varies down the
rows. So the table row base HOISTS out of the per-row loop - the same move
A24's ROWPTR_B made for `row_addr` - and the per-row cost collapses to a clamp,
a shift and two byte reads.

    row   = bottom*15 + (slope+7)          hoisted, once per draw_edge
    entry = local_left + 8                 per row
    addr  = LUT + row*64 + entry*2

The clamp window [-8,15] is verified exhaustively, not assumed: `off` saturates
outside it for every slope and both bottoms, 0 mismatches over local_left in
[-400,400]. The stored value is the word minus the shade-dependent EDGEBASE, so
one 1,920-byte table serves all three shades, and the table is generated BY the
shipped `edge_entry` so it cannot drift from the renderer.

Verified at pose scope against the same oracle A27 used: every run of a pose
against the final 20x18 name table.

    make edge-lut
"""
from __future__ import annotations
import pathlib
import statistics as stt
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from z80core import assemble                            # noqa: E402
import z80_materialize_masked_bench as mb               # noqa: E402
import z80_materialize_dda_bench as dda                 # noqa: E402

CODE = 0x0000
LUT = 0xB000
ROWBASE = 0xC0A0
ROWS, COLS = mb.ROWS, mb.COLS

ANCHOR = "        ld a,l\n        ld (0xc01d),a\nde_rows2:"

HOIST = """        ld a,l
        ld (0xc01d),a
; ---- EDGELUT: hoist the table row out of the per-row loop ----
; bottom and slope are fixed for this whole draw_edge call, so the row base is
; computed once here instead of being rebuilt for every row. A is the slope.
        add a,7                      ; slope + 7 -> 0..14
        ld c,a
        ld a,(0xc01c)                ; BOTTOM
        or a
        jp z,de_lb_top
        ld a,c
        add a,15
        ld c,a
de_lb_top:
        ld a,c
        ld l,a
        ld h,0
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl                    ; row * 64
        ld de,0xB000
        add hl,de
        ld (0xC0A0),hl               ; ROWBASE
de_rows2:"""

LUT_ENTRY = """edge_entry:
; ---- EDGELUT: one clamp, one shift, two byte reads ----
; local_left arrives as a 16-bit signed value at 0xc022. Clamping it to
; [-8,15] is exact, not approximate: `off` saturates outside that window for
; every slope and both bottoms, checked exhaustively over [-400,400].
        ld hl,(0xc022)
        ld a,h
        or a
        jp z,eel_pos
        inc a
        jp z,eel_neg
        bit 7,h
        jp z,eel_hi
        jp eel_lo
eel_pos:
        ld a,l
        cp 16
        jp c,eel_have
        jp eel_hi
eel_neg:
        ld a,l
        cp 0xf8                      ; -8
        jp nc,eel_have
        jp eel_lo
eel_hi:
        ld a,15
        jp eel_have
eel_lo:
        ld a,0xf8
eel_have:
        add a,8                      ; 0..23
        add a,a                      ; entry * 2
        ld e,a
        ld d,0
        ld hl,(0xC0A0)               ; hoisted row base
        add hl,de
        ld e,(hl)
        inc hl
        ld d,(hl)                    ; DE = word - EDGEBASE
        ld hl,(0xc02a)               ; EDGEBASE, already hoisted per run
        add hl,de
        ld (0xc026),hl
        ret

"""


LATE_ANCHOR = ("        cp b\n"
               "        ret c                        ; r1 < r0 -> nothing\n")

# EDGELUT2: the same hoist, moved AFTER the "this edge draws nothing" early
# out. The first placement ran it for every draw_edge call including the ones
# that return immediately.
HOIST_LATE = """; ---- EDGELUT2: the row base, after the empty-edge early out ----
        ld a,(0xc01d)
        add a,7
        ld c,a
        ld a,(0xc01c)
        or a
        jp z,de_lb_top
        ld a,c
        add a,15
        ld c,a
de_lb_top:
        ld a,c
        ld l,a
        ld h,0
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl
        add hl,hl
        ld de,0xB000
        add hl,de
        ld (0xC0A0),hl
"""

# EDGELUT3: the six shifts become one read from a 60-byte table of row bases,
# the same move A24's ROWPTR_B made for row_addr.
HOIST_TAB = """; ---- EDGELUT3: row base from a 60-byte table ----
        ld a,(0xc01d)
        add a,7
        ld c,a
        ld a,(0xc01c)
        or a
        jp z,de_lb_top
        ld a,c
        add a,15
        ld c,a
de_lb_top:
        ld a,c
        ld l,a
        ld h,0
        add hl,hl
        ld de,0xB800
        add hl,de
        ld e,(hl)
        inc hl
        ld d,(hl)
        ld (0xC0A0),de
"""


def build_lut_variant(src, mode=1):
    assert src.count(ANCHOR) == 1
    if mode == 1:
        src = src.replace(ANCHOR, HOIST, 1)
    else:
        assert src.count(LATE_ANCHOR) == 1
        src = src.replace(LATE_ANCHOR,
                          LATE_ANCHOR + (HOIST_LATE if mode == 2 else HOIST_TAB),
                          1)
    # Search for the LABEL, not the name: the routine is preceded by a
    # comment line containing "edge_entry:" and slicing there left the new
    # label inside that comment, so nothing defined it.
    i = src.index("\nedge_entry:") + 1
    j = src.index("; ---- draw_full")
    return src[:i] + LUT_ENTRY + src[j:]


def load_table():
    path = ROOT / "build" / "edge_lut.txt"
    if not path.exists():
        raise SystemExit(f"missing {path} - run `make edge-lut`")
    rows = {}
    for line in path.read_text().splitlines():
        if not line.startswith("ROW"):
            continue
        f = line.split()
        rows[int(f[1])] = [int(v) for v in f[2:]]
    return rows


def main():
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 300
    dump = ROOT / "build" / "coverage_pose_oracle.txt"
    if not dump.exists():
        raise SystemExit(f"missing {dump} - run `make coverage-potential` first")
    lines = [l.split() for l in dump.read_text().splitlines() if l.strip()]
    step = max(1, len(lines) // limit)
    cases = []
    for f in lines[::step]:
        n = int(f[0])
        runs = [tuple(int(v) for v in f[1 + 8 * k: 9 + 8 * k]) for k in range(n)]
        want = [int(v) for v in f[1 + 8 * n:]]
        cases.append((runs, want))

    low, high = mb.tables()
    bgm = mb.background_map()
    rows = load_table()

    results = {}
    for name, src in (("DDA_G", dda.SRC_DDA),
                      ("EDGELUT", build_lut_variant(dda.SRC_DDA, 1)),
                      ("EDGELUT2", build_lut_variant(dda.SRC_DDA, 2)),
                      ("EDGELUT3", build_lut_variant(dda.SRC_DDA, 3))):
        code, _ = assemble(src, CODE)
        img = bytearray(0x10000)
        img[CODE:CODE + len(code)] = code
        img[mb.LOWTAB:mb.LOWTAB + len(low)] = low
        img[mb.HIGHTAB:mb.HIGHTAB + len(high)] = high
        for r, vals in rows.items():
            for i, v in enumerate(vals):
                img[LUT + 64 * r + 2 * i] = v & 0xFF
                img[LUT + 64 * r + 2 * i + 1] = (v >> 8) & 0xFF
        for r in range(30):                      # row-base table for EDGELUT3
            a = LUT + 64 * r
            img[0xB800 + 2 * r] = a & 0xFF
            img[0xB800 + 2 * r + 1] = a >> 8
        fails, ts = 0, []
        for runs, want in cases:
            t, got = mb.run_pose(img, runs, False, bgm)
            ts.append(t)
            if got != want:
                fails += 1
                if fails <= 2:
                    bad = [i for i in range(ROWS * COLS) if got[i] != want[i]]
                    print(f"  MISMATCH {name}: {len(bad)} cells, first "
                          f"r{bad[0] // COLS} c{bad[0] % COLS} "
                          f"want {want[bad[0]]} got {got[bad[0]]}")
        ts.sort()
        n = len(ts)
        results[name] = dict(bytes=len(code), mean=stt.mean(ts),
                             p95=ts[int(0.95 * n)], mx=ts[-1], fails=fails)
        tag = "EXACT" if not fails else f"*** {fails}/{n} POSES WRONG ***"
        print(f"{name:8} {len(code):5d} bytes   {tag}")

    print(f"\n{len(cases)} poses from the A26/A27 pose oracle\n")
    print(f"{'variant':10} {'T/pose':>10} {'p95':>9} {'max':>9} {'bytes':>7}")
    for k, v in results.items():
        print(f"{k:10} {v['mean']:10.1f} {v['p95']:9d} {v['mx']:9d} {v['bytes']:7d}")
    a = results["DDA_G"]
    print()
    for k, v in results.items():
        if k == "DDA_G" or v["fails"]:
            continue
        print(f"  {k:9} vs DDA_G: {100.0 * v['mean'] / a['mean'] - 100:+5.1f}% T"
              f"   {a['mean'] / v['mean']:.3f}x"
              f"   code {v['bytes'] - a['bytes']:+d} bytes"
              f"   baseline 153,450 -> {153450.0 * v['mean'] / a['mean']:.0f} T")
    print("  plus a 1,920-byte edge table (and 60 bytes of row bases for"
          " EDGELUT3)")
    return 1 if any(v["fails"] for v in results.values()) else 0


if __name__ == "__main__":
    sys.exit(main())
