/* GENERATED by tools/race/gen_corpus.py. Do not edit. */
#ifndef CORPUS_HDR_H
#define CORPUS_HDR_H
#include <stdint.h>
#define CORPUS_N 8000
#define CORPUS_BANK_IQ 9
#define CORPUS_BANK_STEP 10
#define CORPUS_BANK_COLS 11
extern const uint16_t gg_corpus_iq[];
extern const uint16_t gg_corpus_step[];
extern const uint8_t gg_corpus_cols[];
#endif
