#!/usr/bin/env python3
"""Emit the canonical inputs and expected move streams for the Z80 race.

All three kernels must reproduce exactly these streams, so the comparison is
between implementations of one function rather than between three different
functions that happen to look similar.

Move encoding, one byte each:
    0 = down one row      1 = next column        2..5 = next column, up 1..4
    6 = run terminator

The packed kernel is handed the stream to copy and is charged NOTHING for
identifying which stream it needs. That is deliberate: it makes packed replay a
floor on what any table-driven approach could cost, not a proposal.
"""
import sys
from pathlib import Path

CHUNK = 6

def col_pair(iq, step, c):
    a0 = iq + 32 + c * step
    a1, a2 = a0 + step, a0 + 2 * step
    h0, h1, h2 = a0 >> 7, a1 >> 7, a2 >> 7
    y0, y1, y2 = 71 - h0, 71 - h1, 71 - h2
    lo0, hi0 = min(y0, y1) >> 3, max(y0, y1) >> 3
    lo1 = min(y1, y2) >> 3
    return hi0 - lo0, lo1 - hi0

def in_domain(iq, step, ncols):
    return all(0 <= (iq + c * step + 32) >> 6 <= 255 for c in range(ncols + 1))

def stream(iq, step, ncols):
    """The move stream for a run of ncols columns, chunked in sixes."""
    out = []
    for c in range(ncols):
        last = (c == ncols - 1)
        nd, jump = col_pair(iq, step, c)
        if nd < 0 or nd > 30:
            return None
        out.extend([0] * nd)
        if last:
            out.append(6)
            break
        if jump > 0 or jump < -4:
            return None
        out.append(1 if jump == 0 else 1 - jump)
    return out

# Every length the renderer produces (see tools/race/span_census.c): the span
# distribution peaks at three to five columns, so timing only 3/6/12/18 would
# weight the measurement towards spans that are comparatively rare.
LENGTHS = list(range(1, 21))
STEPS = [37, 61, 97, 143, 205, 251, 287, 331, 410, 461, 512, 587, 631, 703, 743, 787,
         -61, -143, -287, -410, -512, -631]

cases = []
for st in STEPS:
    # centre the run so every tested length stays inside the uint8 depth domain
    span = 21 * abs(st)
    iq = max(0, (16383 - span) // 2)
    if st < 0:
        iq = min(16383 - 32, iq + span)
    if all(in_domain(iq, st, n + 1) and stream(iq, st, n) is not None for n in LENGTHS):
        cases.append((iq, st))
if len(cases) < 8:
    sys.exit(f"only {len(cases)} usable cases; widen the step list")

out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("tools/race/race_data.h")
L = ["/* GENERATED by tools/race/gen_race_data.py. Do not edit. */",
     "#ifndef RACE_DATA_H", "#define RACE_DATA_H", "#include <stdint.h>",
     f"#define RACE_NCASE {len(cases)}", f"#define RACE_NLEN {len(LENGTHS)}",
     f"static const uint8_t k_race_len[RACE_NLEN] = {{{','.join(str(n) for n in LENGTHS)}}};",
     "static const int16_t k_race_iq[RACE_NCASE] = {" + ",".join(str(c[0]) for c in cases) + "};",
     "static const int16_t k_race_step[RACE_NCASE] = {" + ",".join(str(c[1]) for c in cases) + "};"]

blob, offs, lens = [], [], []
for li, n in enumerate(LENGTHS):
    for ci, (iq, st) in enumerate(cases):
        s = stream(iq, st, n)
        offs.append(len(blob)); lens.append(len(s)); blob.extend(s)
L.append(f"#define RACE_BLOB {len(blob)}")
L.append("static const uint16_t k_race_off[RACE_NLEN*RACE_NCASE] = {" + ",".join(map(str, offs)) + "};")
L.append("static const uint8_t k_race_mlen[RACE_NLEN*RACE_NCASE] = {" + ",".join(map(str, lens)) + "};")
L.append("static const uint8_t k_race_blob[RACE_BLOB] = {" + ",".join(map(str, blob)) + "};")
L.append("#endif")
out.write_text("\n".join(L) + "\n")
print(f"wrote {out}: {len(cases)} cases x {len(LENGTHS)} lengths, "
      f"{len(blob)} move bytes, max stream {max(lens)}")
