/* Generate the selector ROM tables, and price the two record philosophies.
 *
 * The census established the fact this rests on: across the whole reachable
 * domain a step has AT MOST EIGHT phase bands, and all but thirteen steps have
 * exactly eight. A hard, tiny, almost-always-saturated maximum is unusual, and
 * it changes the representation question. When the count varies wildly you pack,
 * because padding to the worst case wastes most of the ROM. When the count is
 * always the maximum, padding wastes almost nothing and buys addressing that is
 * a shift instead of a pointer chase.
 *
 * So this tool prices both philosophies rather than assuming one:
 *
 *   FIXED    eight slots per step, always, split into two parallel arrays:
 *            sixteen bytes of thresholds and eight bytes of body ids. A step's
 *            record address is the step ordinal shifted left four (or three).
 *            Sixteen and eight both divide sixteen kilobytes, so a record can
 *            never straddle a cartridge bank and the bank number is a shift too.
 *
 *   PACKED   a variable-length record per step, three bytes per band, stored
 *            highest threshold first so a forward scan stops at the first match,
 *            plus a two-byte pointer per step to find it. Records are padded at
 *            bank boundaries, because a record that straddles a bank would need
 *            a straddle test on every fetch and that costs more than the padding.
 *
 * It emits the Game Gear tables for the race cases, and reports what the full
 * domain would cost in both layouts.
 *
 * Bodies here are FAMILY ZERO only -- the descending-row family the race kernels
 * use. The census interned a signature over both families, which makes its body
 * count finer than the one a family-zero replay needs.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tilesector_polar_renderer.c"
#include "dp_tables.h"
#include "race_data.h"

#define BIAS   65536L
#define NPH    1024
#define MAXSLOT 8
#define BANKB  16384
#define FULL_BANK0 2   /* the stress ROM parks the production records here */

/* ---- the reachable step set, exactly as the census derives it ------------ */
static int16_t g_step[8192]; static int g_nstep=0;
static void build_steps(void)
{
    static unsigned char seen[65536],sf_seen[256];
    int cls,yaw,invd,sf,v;
    for(cls=0;cls<7;++cls) for(yaw=0;yaw<256;++yaw) sf_seen[(uint8_t)k_depth_stepfac_q4[cls][yaw]]=1;
    for(sf=0;sf<256;++sf){ if(!sf_seen[sf]) continue;
        for(invd=0;invd<256;++invd){
            int16_t s=shr_signed((int16_t)((int16_t)invd*(int16_t)(int8_t)sf),4);
            for(v=0;v<2;++v){ int16_t x=v?(int16_t)-s:s;
                if(!seen[(uint16_t)x]&&g_nstep<8192){ seen[(uint16_t)x]=1; g_step[g_nstep++]=x; } } } }
}

/* ---- the six-column body at (phase, step), family zero ------------------- */
static int body6(int phase,int step,unsigned char *p)
{
    int c;
    for(c=0;c<6;++c){
        long a0=BIAS+(long)phase+(long)c*step,a1=a0+step,a2=a1+step;
        long y0=71-(a0>>7),y1=71-(a1>>7),y2=71-(a2>>7);
        long lo0=(y0<y1?y0:y1)>>3,hi0=(y0<y1?y1:y0)>>3;
        long lo1=(y1<y2?y1:y2)>>3;
        long nd=hi0-lo0,jump=lo1-hi0;
        if(nd<0||nd>30||jump>0||jump<-4) return 0;
        p[c]=(unsigned char)((nd<<3)|(unsigned char)(-jump));
    }
    return 1;
}

/* ---- body interning ------------------------------------------------------ */
static unsigned char g_desc[4096][6]; static int g_nbody=0;
static int intern(const unsigned char *p)
{
    int i;
    for(i=0;i<g_nbody;++i) if(!memcmp(g_desc[i],p,6)) return i;
    if(g_nbody>=4096){ fprintf(stderr,"body table overflow\n"); exit(1); }
    memcpy(g_desc[g_nbody],p,6); return g_nbody++;
}

/* merged contiguous phase bands for one step: thresholds and body ids */
static int bands_of(int step,int *thr,int *bod)
{
    int ph,n=0,prev=-1;
    for(ph=0;ph<NPH;++ph){
        unsigned char p[6]; int b;
        if(!body6(ph,step,p)){ fprintf(stderr,"step %d phase %d has no family-zero body\n",step,ph); exit(1); }
        b=intern(p);
        if(b!=prev){ if(n>=MAXSLOT){ fprintf(stderr,"step %d exceeds %d bands\n",step,MAXSLOT); exit(1);} 
                     thr[n]=ph; bod[n]=b; ++n; prev=b; } }
    return n;
}

static void emit_head(FILE*f,int bank)
{
    fprintf(f,"/* GENERATED by tools/race/gen_selector_tables.c. Do not edit. */\n");
    fprintf(f,"#include <stdint.h>\n");
    if(bank>=0) fprintf(f,"#ifdef __SDCC\n#pragma codeseg LIT_%d\n#endif\n",bank);
    fprintf(f,"\n");
}
static void emit_bytes(FILE*f,const char*name,const unsigned char*d,size_t n)
{
    size_t i;
    fprintf(f,"const uint8_t %s[%lu] = {",name,(unsigned long)n);
    for(i=0;i<n;++i){ if(!(i&15)) fprintf(f,"\n "); fprintf(f,"0x%02X,",d[i]); }
    fprintf(f,"\n};\n\n");
}

int main(int argc,char**argv)
{
    const char *od = argc>1?argv[1]:"tools/race";
    int full = (argc>2 && !strcmp(argv[2],"--full"));
    char path[512]; FILE *f;
    int si,i,j;
    int ex_step[64],ex_bands[64],nex=0;
    /* "exceptional" means well below the saturated count, not merely one short:
     * seven-band steps are the ordinary other half of the population. */
    const int EXCEPTIONAL=7;
    long tot_bands=0; int hist[MAXSLOT+1]; 
    int hi_used[256]; int nhi=0;

    memset(hist,0,sizeof hist);
    memset(hi_used,0,sizeof hi_used);
    build_steps();

    /* ---- full-domain accounting ---- */
    for(si=0;si<g_nstep;++si){
        int thr[MAXSLOT],bod[MAXSLOT],n=bands_of(g_step[si],thr,bod);
        tot_bands+=n; ++hist[n];
        if(n<EXCEPTIONAL && nex<64){ ex_step[nex]=g_step[si]; ex_bands[nex]=n; ++nex; }
        if(!hi_used[((uint16_t)g_step[si])>>8]){ hi_used[((uint16_t)g_step[si])>>8]=1; ++nhi; }
    }

    printf("selector table generator\n");
    printf("  reachable steps %d, distinct family-zero six-column bodies %d\n",g_nstep,g_nbody);
    printf("  band histogram:");
    for(i=1;i<=MAXSLOT;++i) if(hist[i]) printf("  %d band%s: %d step%s",i,i==1?"":"s",hist[i],hist[i]==1?"":"s");
    printf("\n  total bands %ld, eight-slot capacity %d, padding waste %d slots (%.3f%%)\n",
           tot_bands,g_nstep*MAXSLOT,g_nstep*MAXSLOT-(int)tot_bands,
           100.0*(g_nstep*MAXSLOT-(double)tot_bands)/(g_nstep*MAXSLOT));

    printf("\n  the %d exceptional steps (fewer than seven bands)\n",nex);
    for(i=0;i<nex;++i) printf("    step %6d  %d band%s\n",ex_step[i],ex_bands[i],ex_bands[i]==1?"":"s");

    /* ROM accounting, full domain.
     *
     * Both layouts store the same slot: two threshold bytes and one body byte.
     * The ONLY differences are how a step's record is found and how the scan
     * knows where to stop, and that is what makes the comparison sharp:
     *
     *   FIXED   eight slots always, ascending, base = ordinal * 24. Padding
     *           slots carry threshold 0xFFFF, which a descending scan skips and
     *           an ascending binary search treats as "above everything".
     *   PACKED  n slots, descending, base from a two-byte pointer. The last
     *           slot's threshold is zero, so the scan terminates by itself and
     *           no count byte is needed.
     *
     * So per chunk the two scans are the same instructions. What differs is
     * ROM, the per-span base formation, and whether a record can straddle a
     * cartridge bank.
     */
    {
        long ffix=(long)g_nstep*24;
        long fpad=0, cur=0;
        long ppak=0, ppad=0, pcur=0;
        for(si=0;si<g_nstep;++si){
            int thr[MAXSLOT],bod[MAXSLOT],n=bands_of(g_step[si],thr,bod);
            long rec=3*(long)n;
            if((cur%BANKB)+24>BANKB){ long pad=BANKB-(cur%BANKB); fpad+=pad; cur+=pad; }
            cur+=24;
            if((pcur%BANKB)+rec>BANKB){ long pad=BANKB-(pcur%BANKB); ppad+=pad; pcur+=pad; }
            pcur+=rec; ppak+=rec; }
        printf("\n  ROM, whole reachable domain (both layouts store the same slot:\n");
        printf("  two threshold bytes and one body byte, so this is a like-for-like count)\n");
        printf("    FIXED   %ld steps x 24 B = %ld B, bank padding %ld B, total %ld B (%.1f KiB), %ld banks\n",
               (long)g_nstep,ffix,fpad,ffix+fpad,(ffix+fpad)/1024.0,(cur+BANKB-1)/BANKB);
        printf("    PACKED  %ld slots x 3 B = %ld B, bank padding %ld B, pointers %ld B, total %ld B (%.1f KiB), %ld banks\n",
               tot_bands,ppak,ppad,(long)g_nstep*2,ppak+ppad+(long)g_nstep*2,
               (ppak+ppad+(long)g_nstep*2)/1024.0,(pcur+BANKB-1)/BANKB+((long)g_nstep*2+BANKB-1)/BANKB);
        printf("    body descriptors, shared by both (stream + prefix + pointer) reported below\n");
        printf("    step high bytes actually reachable: %d of 256, so the step-to-ordinal\n",nhi);
        printf("    map is 256 B of page index plus %d B of pages\n",nhi*256*2);
        printf("\n    FIXED costs %+.1f%% of PACKED. Padding to eight wastes %ld slots (%.2f%%),\n",
               100.0*(ffix+fpad)/(double)(ppak+ppad+(long)g_nstep*2)-100.0,
               (long)g_nstep*MAXSLOT-tot_bands,
               100.0*((long)g_nstep*MAXSLOT-tot_bands)/((double)g_nstep*MAXSLOT));
        printf("    but the two-byte pointer PACKED needs costs %ld B, which is most of\n",(long)g_nstep*2);
        printf("    what packing reclaims. The band count is not saturated -- half the steps\n");
        printf("    use seven slots, not eight -- so this is a real trade, not a walkover.\n");
        printf("    FIXED's records never straddle a bank for %ld B of boundary padding;\n",fpad);
        printf("    PACKED needs %ld B for the same property.\n",ppad);
        printf("    The addressing argument is weaker than it looks: three bytes a slot\n");
        printf("    makes the record stride 24, which is not a power of two, so forming\n");
        printf("    a FIXED base is five shifts and adds rather than one shift. Splitting\n");
        printf("    thresholds and bodies into 16-byte and 8-byte arrays would restore the\n");
        printf("    shift, at the cost of turning the hit back into an index; that variant\n");
        printf("    is not measured here.\n");
    }

    /* ---- scan length: where FIXED loses cycles and PACKED loses bytes -----
     *
     * Both scans are the same instructions. The difference is where they start.
     * PACKED starts at its own highest band. FIXED starts at slot seven, so on a
     * step with seven bands it steps over one padding slot before it reaches any
     * real threshold, and on the thirteen degenerate steps it steps over several.
     * That is the padding showing up as cycles instead of bytes, and it is the
     * only per-chunk difference between the two layouts.
     *
     * Weighted by phase, because a wide band is entered more often than a narrow
     * one, and the renderer's phases are not concentrated anywhere in particular.
     */
    {
        double tf=0.0, tp=0.0; long nph=0;
        double wf=0.0; int wstep=0;
        for(si=0;si<g_nstep;++si){
            int thr[MAXSLOT],bod[MAXSLOT],n=bands_of(g_step[si],thr,bod),k,ph;
            double sf=0.0;
            for(k=0;k<n;++k){
                int lo=thr[k], hi=(k+1<n)?thr[k+1]:NPH, w=hi-lo;
                /* FIXED walks slot 7 down to slot k; PACKED walks slot n-1 down to k */
                tf += (double)w*(double)(8-k);
                tp += (double)w*(double)(n-k);
                sf += (double)w*(double)((8-k)-(n-k));
                nph += w; }
            sf/=NPH;
            if(sf>wf){ wf=sf; wstep=g_step[si]; } }
        printf("\n  scan length, weighted by phase over the whole domain\n");
        printf("    FIXED  %.3f slots examined per lookup\n",tf/nph);
        printf("    PACKED %.3f slots examined per lookup\n",tp/nph);
        printf("    FIXED examines %.3f more, which is exactly the padding it starts on;\n",(tf-tp)/nph);
        printf("    worst step %d pays %.2f extra slots per lookup\n",wstep,wf);
        printf("    PACKED pays one pointer load per span for its base; FIXED pays\n");
        printf("    %.3f extra scan steps per chunk plus the arithmetic for a stride of\n",(tf-tp)/nph);
        printf("    24, which is NOT a power of two and so is not the cheap shift the\n");
        printf("    fixed-size argument assumes. Neither is free; the race says which\n");
        printf("    one the Z80 minds more.\n");
    }

    /* ---- full-domain production tables --------------------------------
     *
     * The race only ever held 22 steps, all of them inside one bank, so its
     * pointer was a two-byte offset and its bank was a constant. At full domain
     * the records occupy five banks, and that changes both layouts' arithmetic
     * in ways the race could not see:
     *
     *   PACKED  a step's record now needs a BANK as well as an offset. Three
     *           bytes, not two, because 14 bits of in-bank address plus a bank
     *           index does not fit in 16. That is 3,103 x 3 B, not x 2 B.
     *   FIXED   base = ordinal * 24 overflows 16 bits past ordinal 2730, and
     *           24 does not divide 16384, so the bank cannot be a shift of the
     *           ordinal. It needs a division, a per-step pointer (which throws
     *           away the entire reason for the fixed layout), or power-of-two
     *           bank packing that wastes 4 KB a bank.
     *
     * So the full-domain accounting below supersedes the race-scale figures.
     *
     * The runtime map is also merged here: rather than step -> ordinal ->
     * pointer, one three-byte entry gives the bank and the in-bank address
     * directly, so a span pays two bank switches and one read.
     */
    if(full){
        long nrec=0, pad=0, cur=0, bank=0;
        unsigned char *bankbuf[16]; int banklen[16], nbank=0;
        unsigned char *ptr3;
        int hipage[256], npage=0;
        unsigned char *mappage;
        int b;
        for(b=0;b<16;++b){ bankbuf[b]=(unsigned char*)malloc(BANKB); banklen[b]=0; }
        ptr3=(unsigned char*)calloc((size_t)g_nstep*3,1);
        for(i=0;i<256;++i) hipage[i]=-1;

        for(si=0;si<g_nstep;++si){
            int thr[MAXSLOT],bod[MAXSLOT],n=bands_of(g_step[si],thr,bod),k;
            int rec=3*n;
            if(banklen[bank]+rec>BANKB){ pad+=BANKB-banklen[bank]; ++bank;
                if(bank>=16){ fprintf(stderr,"packed records exceed 16 banks\n"); return 1; } }
            ptr3[si*3+0]=(unsigned char)bank;
            ptr3[si*3+1]=(unsigned char)(banklen[bank]&255);
            ptr3[si*3+2]=(unsigned char)(banklen[bank]>>8);
            for(k=n-1;k>=0;--k){
                bankbuf[bank][banklen[bank]++]=(unsigned char)((thr[k]>>8)&255);
                bankbuf[bank][banklen[bank]++]=(unsigned char)(thr[k]&255);
                bankbuf[bank][banklen[bank]++]=(unsigned char)bod[k]; }
            nrec+=rec;
            if(hipage[((uint16_t)g_step[si])>>8]<0) hipage[((uint16_t)g_step[si])>>8]=npage++;
        }
        nbank=(int)bank+1;

        /* the merged map: step high byte picks a page, step low byte gives the
         * bank and in-bank address of that step's record in one three-byte read */
        mappage=(unsigned char*)calloc((size_t)npage*768,1);
        for(si=0;si<g_nstep;++si){
            int pg=hipage[((uint16_t)g_step[si])>>8], lo=((uint16_t)g_step[si])&255;
            memcpy(mappage+(size_t)pg*768+(size_t)lo*3, ptr3+(size_t)si*3, 3); }

        printf("\n  FULL-DOMAIN production tables (these supersede the race-scale\n");
        printf("  pointer accounting above, which only ever spanned one bank)\n");
        printf("    PACKED records %ld B in %d banks, boundary padding %ld B\n",nrec,nbank,pad);
        printf("    step map %d pages x 768 B = %d B (bank + in-bank address per step)\n",
               npage,npage*768);
        printf("    page index 256 B, body stream/pointer/prefix tables in the fixed bank\n");
        printf("    total banked %ld B (%.1f KiB) in %d banks\n",
               nrec+pad+(long)npage*768,(nrec+pad+(long)npage*768)/1024.0,nbank+1);
        printf("    A span pays two bank switches and one three-byte read; the step does\n");
        printf("    not change inside a span, so both are per span, not per chunk.\n");
        printf("\n    Correction to the race-scale FIXED figure: a 24-byte stride cannot\n");
        printf("    derive its bank by shifting, and ordinal*24 overflows 16 bits past\n");
        printf("    ordinal 2730. Splitting into 16-byte threshold and 8-byte body arrays\n");
        printf("    fixes both (1024 and 2048 records a bank exactly) and is the only\n");
        printf("    FIXED variant that survives banking, but it was not the one raced.\n");

        for(b=0;b<nbank;++b){
            snprintf(path,sizeof path,"%s/selfull_b%d.c",od,b); f=fopen(path,"w");
            emit_head(f,FULL_BANK0+b);
            { char nm[64]; snprintf(nm,sizeof nm,"gg_selfull_rec%d",b);
              emit_bytes(f,nm,bankbuf[b],(size_t)banklen[b]); }
            fclose(f); }
        snprintf(path,sizeof path,"%s/selfull_map.c",od); f=fopen(path,"w");
        emit_head(f,FULL_BANK0+nbank);
        emit_bytes(f,"gg_selfull_map",mappage,(size_t)npage*768);
        fclose(f);
        /* the page index is 256 bytes and every span reads it, so it belongs in
         * the fixed bank alongside the body tables, not behind a switch */
        snprintf(path,sizeof path,"%s/selfull_hi.c",od); f=fopen(path,"w");
        emit_head(f,-1);
        { static unsigned char d[256];
          for(i=0;i<256;++i) d[i]=(unsigned char)(hipage[i]<0?0xFF:hipage[i]);
          emit_bytes(f,"gg_selfull_hi",d,256); }
        fclose(f);
        snprintf(path,sizeof path,"%s/selfull_hdr.h",od); f=fopen(path,"w");
        fprintf(f,"/* GENERATED by tools/race/gen_selector_tables.c --full. Do not edit. */\n");
        fprintf(f,"#ifndef SELFULL_H\n#define SELFULL_H\n#include <stdint.h>\n");
        fprintf(f,"#define SELFULL_NSTEP %d\n#define SELFULL_NBANK %d\n",g_nstep,nbank);
        fprintf(f,"#define SELFULL_NPAGE %d\n#define SELFULL_BANK0 %d\n",npage,FULL_BANK0);
        fprintf(f,"#define SELFULL_MAPBANK %d\n",FULL_BANK0+nbank);
        fprintf(f,"#define SELFULL_STEPBANK %d\n",FULL_BANK0+nbank+1);
        fprintf(f,"extern const uint8_t gg_selfull_steps[];\n");
        for(b=0;b<nbank;++b) fprintf(f,"extern const uint8_t gg_selfull_rec%d[];\n",b);
        fprintf(f,"extern const uint8_t gg_selfull_map[];\n");
        fprintf(f,"extern const uint8_t gg_selfull_hi[];\n");
        fprintf(f,"extern const uint8_t gg_sel_bstream[];\n");
        fprintf(f,"extern const uint8_t gg_sel_bptr[];\n");
        fprintf(f,"extern const uint8_t gg_sel_bpre[];\n");
        fprintf(f,"#endif\n");
        fclose(f);
        /* the host needs the same tables to validate exhaustively */
        snprintf(path,sizeof path,"%s/selfull_steps.h",od); f=fopen(path,"w");
        fprintf(f,"/* GENERATED. The reachable step set, in ordinal order. */\n");
        fprintf(f,"#ifndef SELFULL_STEPS_H\n#define SELFULL_STEPS_H\n#include <stdint.h>\n");
        fprintf(f,"static const int16_t k_selfull_step[%d] = {",g_nstep);
        for(si=0;si<g_nstep;++si){ if(!(si&15)) fprintf(f,"\n "); fprintf(f,"%d,",g_step[si]); }
        fprintf(f,"\n};\n#endif\n");
        fclose(f);
        /* the stress ROM needs the reachable step set on the cartridge: the map
         * is zero-filled for unreachable steps, so it cannot be used to decide
         * reachability, only to resolve a step already known to be reachable */
        snprintf(path,sizeof path,"%s/selfull_steps.c",od); f=fopen(path,"w");
        emit_head(f,FULL_BANK0+nbank+1);
        { unsigned char *d=(unsigned char*)malloc((size_t)g_nstep*2);
          for(si=0;si<g_nstep;++si){ d[si*2]=(unsigned char)((uint16_t)g_step[si]&255);
                                     d[si*2+1]=(unsigned char)(((uint16_t)g_step[si])>>8); }
          emit_bytes(f,"gg_selfull_steps",d,(size_t)g_nstep*2); free(d); }
        fclose(f);
        free(ptr3); free(mappage);
        for(b=0;b<16;++b) free(bankbuf[b]);
    }

    /* ---- race tables ---- */
    {
        int ord[RACE_NCASE];
        unsigned char a0[RACE_NCASE][NPH];
        unsigned char fix[RACE_NCASE*24];
        unsigned char pblob[RACE_NCASE*24]; int poff[RACE_NCASE]; int pn=0;
        int hipage[256]; int npage=0;
        unsigned char *lopage;
        /* the replayable body: the move stream itself, so a chunk is one LDIR.
         * The packed-replay comparator already proved LDIR is the floor for
         * emitting moves, so every selector uses it and the difference between
         * a selector and that comparator is exactly the selector's own cost. */
        unsigned char bstream[4096*32]; int bsn=0;
        int bptr[4096]; unsigned char bpre[4096*8];
        int maxstream=0;

        for(si=0;si<RACE_NCASE;++si) ord[si]=si;
        for(i=0;i<256;++i) hipage[i]=-1;

        for(si=0;si<RACE_NCASE;++si){
            int st=k_race_step[si], thr[MAXSLOT],bod[MAXSLOT],n,ph;
            n=bands_of(st,thr,bod);
            for(ph=0;ph<NPH;++ph){ unsigned char p6[6]; body6(ph,st,p6); a0[si][ph]=(unsigned char)intern(p6); }
            /* FIXED: eight slots, ascending, padded */
            for(i=0;i<MAXSLOT;++i){
                int t = i<n ? thr[i] : 0xFFFF;
                int b = i<n ? bod[i] : bod[n-1];
                /* high byte first: the scan compares it before it needs the low
                 * byte, so the loop never has to hold a byte in a register and
                 * the output pointer can stay in DE untouched. */
                fix[si*24+i*3+0]=(unsigned char)((t>>8)&255);
                fix[si*24+i*3+1]=(unsigned char)(t&255);
                fix[si*24+i*3+2]=(unsigned char)b; }
            /* PACKED: n slots, descending, last threshold zero terminates the scan */
            poff[si]=pn;
            for(i=n-1;i>=0;--i){ pblob[pn++]=(unsigned char)((thr[i]>>8)&255);
                                 pblob[pn++]=(unsigned char)(thr[i]&255);
                                 pblob[pn++]=(unsigned char)bod[i]; }
            if(hipage[((uint16_t)st)>>8]<0) hipage[((uint16_t)st)>>8]=npage++;
        }
        if(g_nbody>255){ fprintf(stderr,"body id does not fit a byte\n"); return 1; }

        /* body streams and their per-column prefix lengths */
        for(i=0;i<g_nbody;++i){
            int c,k=0; bptr[i]=bsn;
            for(c=0;c<6;++c){
                int v=g_desc[i][c], nd=v>>3, jp=v&7, d;
                for(d=0;d<nd;++d) bstream[bsn+k++]=0;
                /* prefix for a chunk that TERMINATES on column c: the downs are
                 * emitted, then the run terminator replaces the jump byte */
                bpre[i*8+c]=(unsigned char)k;
                bstream[bsn+k++]=(unsigned char)(1+jp); }
            if(k>maxstream) maxstream=k;
            bsn+=k; }

        lopage=(unsigned char*)calloc((size_t)npage*512,1);
        for(si=0;si<RACE_NCASE;++si){
            int pg=hipage[((uint16_t)k_race_step[si])>>8], lo=((uint16_t)k_race_step[si])&255;
            lopage[(size_t)pg*512+lo*2+0]=(unsigned char)(ord[si]&255);
            lopage[(size_t)pg*512+lo*2+1]=(unsigned char)(ord[si]>>8); }

        /* banks 2 and 3: the A0 exact-state table, 1024 bytes per step ordinal.
         * 1024 divides 16384, so a step's row never straddles a bank and the
         * bank number is the ordinal's high nibble -- the same fixed-size
         * addressing argument, one level up. */
        snprintf(path,sizeof path,"%s/sel_b2.c",od); f=fopen(path,"w"); emit_head(f,2);
        { static unsigned char buf[16*NPH]; int k=0;
          for(si=0;si<16&&si<RACE_NCASE;++si){ memcpy(buf+k,a0[si],NPH); k+=NPH; }
          emit_bytes(f,"gg_sel_a0_0",buf,(size_t)k); }
        fclose(f);
        snprintf(path,sizeof path,"%s/sel_b3.c",od); f=fopen(path,"w"); emit_head(f,3);
        { static unsigned char buf[16*NPH]; int k=0;
          for(si=16;si<RACE_NCASE;++si){ memcpy(buf+k,a0[si],NPH); k+=NPH; }
          emit_bytes(f,"gg_sel_a0_1",buf,(size_t)k); }
        fclose(f);
        snprintf(path,sizeof path,"%s/sel_b4.c",od); f=fopen(path,"w"); emit_head(f,4);
        emit_bytes(f,"gg_sel_fix",fix,(size_t)RACE_NCASE*24);
        fclose(f);
        snprintf(path,sizeof path,"%s/sel_b5.c",od); f=fopen(path,"w"); emit_head(f,5);
        emit_bytes(f,"gg_sel_pblob",pblob,(size_t)pn);
        fclose(f);
        snprintf(path,sizeof path,"%s/sel_b6.c",od); f=fopen(path,"w"); emit_head(f,6);
        emit_bytes(f,"gg_sel_a1lo",lopage,(size_t)npage*512);
        fclose(f);
        /* bank 0: the small hot tables every selector shares. A real build keeps
         * these in the fixed bank so no selector pays a switch to reach them. */
        snprintf(path,sizeof path,"%s/sel_b0.c",od); f=fopen(path,"w"); emit_head(f,-1);
        emit_bytes(f,"gg_sel_bstream",bstream,(size_t)bsn);
        { static unsigned char d[4096*2];
          for(i=0;i<g_nbody;++i){ d[i*2]=(unsigned char)(bptr[i]&255); d[i*2+1]=(unsigned char)(bptr[i]>>8); }
          emit_bytes(f,"gg_sel_bptr",d,(size_t)g_nbody*2); }
        emit_bytes(f,"gg_sel_bpre",bpre,(size_t)g_nbody*8);
        { static unsigned char d[RACE_NCASE*2];
          for(i=0;i<RACE_NCASE;++i){ d[i*2]=(unsigned char)(poff[i]&255); d[i*2+1]=(unsigned char)(poff[i]>>8); }
          emit_bytes(f,"gg_sel_poff",d,(size_t)RACE_NCASE*2); }
        { static unsigned char d[256];
          for(i=0;i<256;++i) d[i]=(unsigned char)(hipage[i]<0?0xFF:hipage[i]);
          emit_bytes(f,"gg_sel_a1hi",d,256); }
        fclose(f);

        snprintf(path,sizeof path,"%s/selector_tables.h",od); f=fopen(path,"w");
        fprintf(f,"/* GENERATED by tools/race/gen_selector_tables.c. Do not edit. */\n");
        fprintf(f,"#ifndef SELECTOR_TABLES_H\n#define SELECTOR_TABLES_H\n#include <stdint.h>\n\n");
        fprintf(f,"#define SEL_NSTEP  %d\n",RACE_NCASE);
        fprintf(f,"#define SEL_NBODY  %d\n",g_nbody);
        fprintf(f,"#define SEL_NPAGE  %d\n",npage);
        fprintf(f,"#define SEL_PBLOB  %d\n",pn);
        fprintf(f,"#define SEL_BANK_A0_0 2\n#define SEL_BANK_A0_1 3\n");
        fprintf(f,"#define SEL_BANK_FIX  4\n#define SEL_BANK_PAK  5\n#define SEL_BANK_A1   6\n");
        fprintf(f,"extern const uint8_t gg_sel_a0_0[];\nextern const uint8_t gg_sel_a0_1[];\n");
        fprintf(f,"extern const uint8_t gg_sel_fix[];\nextern const uint8_t gg_sel_pblob[];\n");
        fprintf(f,"extern const uint8_t gg_sel_a1lo[];\nextern const uint8_t gg_sel_bstream[];\n");
        fprintf(f,"extern const uint8_t gg_sel_bptr[];\nextern const uint8_t gg_sel_bpre[];\n");
        fprintf(f,"extern const uint8_t gg_sel_poff[];\nextern const uint8_t gg_sel_a1hi[];\n");
        fprintf(f,"#endif\n");
        fclose(f);

        printf("\n  race tables: %d steps, %d bodies, packed blob %d B, fixed %d B,\n",
               RACE_NCASE,g_nbody,pn,RACE_NCASE*24);
        printf("    A0 exact-state %d B, A1 pages %d, body streams %d B (longest %d),\n",
               RACE_NCASE*NPH,npage,bsn,maxstream);
        printf("    body pointers %d B, body prefixes %d B\n",g_nbody*2,g_nbody*8);
    }
    return 0;
}
