#!/usr/bin/env python3
"""Bake a uniform sample of the renderer's REAL raster tuples into the cartridge.

Weighting the per-length race timings by the span-length histogram fixes one bias
and leaves another: within a length, the race sampled (step, phase) from 21
hand-chosen steps at centred accumulators. The linear scan's cost depends on
which of the eight phase bands is hit, and the replay's cost on how many move
bytes the body expands to. Both vary with (step, phase), so a length-weighted
projection is still a model.

This removes the model. It samples actual (iq, step, columns) tuples produced by
the pose corpus, uniformly and with a fixed seed, and the ROM replays exactly
those through both kernels. Summing the measured cycles over a uniform sample is
an unbiased estimate of the mean over the whole corpus, and the standard error is
reported rather than assumed.
"""
import csv, random, sys
from pathlib import Path

N = int(sys.argv[3]) if len(sys.argv) > 3 else 8000
SEED = 20260918
src = Path(sys.argv[1] if len(sys.argv) > 1 else "build/race/corpus_tuples.csv")
out = Path(sys.argv[2] if len(sys.argv) > 2 else "tools/race")

rows = [(int(r["iq"]), int(r["step"]), int(r["cols"])) for r in csv.DictReader(src.open())]
if len(rows) < N:
    sys.exit(f"corpus has only {len(rows)} tuples, need {N}")
rng = random.Random(SEED)
samp = rng.sample(rows, N)

# the sample must look like the corpus, or the estimate is of the wrong thing
def hist(rs):
    h = {}
    for _, _, c in rs: h[c] = h.get(c, 0) + 1
    return h
hc, hs = hist(rows), hist(samp)
worst = max(abs(100*hs.get(c,0)/N - 100*hc[c]/len(rows)) for c in hc)
print(f"corpus {len(rows):,} tuples, sample {N:,}, seed {SEED}")
print(f"  largest span-length share discrepancy: {worst:.2f} percentage points")
print(f"  mean columns  corpus {sum(c for _,_,c in rows)/len(rows):.3f}  "
      f"sample {sum(c for _,_,c in samp)/N:.3f}")
print(f"  mean |step|   corpus {sum(abs(s) for _,s,_ in rows)/len(rows):.1f}  "
      f"sample {sum(abs(s) for _,s,_ in samp)/N:.1f}")

def emit(path, bank, name, data, width):
    L = ["/* GENERATED by tools/race/gen_corpus.py. Do not edit. */",
         "#include <stdint.h>", f"#ifdef __SDCC", f"#pragma codeseg LIT_{bank}", "#endif", ""]
    t = "uint16_t" if width == 2 else "uint8_t"
    L.append(f"const {t} {name}[{len(data)}] = {{")
    for i in range(0, len(data), 12):
        L.append("  " + ",".join(str(x & (0xFFFF if width == 2 else 0xFF)) for x in data[i:i+12]) + ",")
    L.append("};")
    Path(path).write_text("\n".join(L) + "\n")

emit(out / "corpus_b9.c",  9,  "gg_corpus_iq",   [t[0] for t in samp], 2)
emit(out / "corpus_b10.c", 10, "gg_corpus_step", [t[1] for t in samp], 2)
emit(out / "corpus_b11.c", 11, "gg_corpus_cols", [t[2] for t in samp], 1)
(out / "corpus_hdr.h").write_text(
    "/* GENERATED by tools/race/gen_corpus.py. Do not edit. */\n"
    "#ifndef CORPUS_HDR_H\n#define CORPUS_HDR_H\n#include <stdint.h>\n"
    f"#define CORPUS_N {N}\n#define CORPUS_BANK_IQ 9\n#define CORPUS_BANK_STEP 10\n"
    "#define CORPUS_BANK_COLS 11\n"
    "extern const uint16_t gg_corpus_iq[];\nextern const uint16_t gg_corpus_step[];\n"
    "extern const uint8_t gg_corpus_cols[];\n#endif\n")
print(f"  wrote {out}/corpus_b9.c, corpus_b10.c, corpus_b11.c, corpus_hdr.h")
