/* GENERATED by tools/race/gen_selector_tables.c. Do not edit. */
#ifndef SELECTOR_TABLES_H
#define SELECTOR_TABLES_H
#include <stdint.h>

#define SEL_NSTEP  21
#define SEL_NBODY  146
#define SEL_NPAGE  6
#define SEL_PBLOB  453
#define SEL_BANK_A0_0 2
#define SEL_BANK_A0_1 3
#define SEL_BANK_FIX  4
#define SEL_BANK_PAK  5
#define SEL_BANK_A1   6
extern const uint8_t gg_sel_a0_0[];
extern const uint8_t gg_sel_a0_1[];
extern const uint8_t gg_sel_fix[];
extern const uint8_t gg_sel_pblob[];
extern const uint8_t gg_sel_a1lo[];
extern const uint8_t gg_sel_bstream[];
extern const uint8_t gg_sel_bptr[];
extern const uint8_t gg_sel_bpre[];
extern const uint8_t gg_sel_poff[];
extern const uint8_t gg_sel_a1hi[];
#endif
