/* GENERATED by tools/race/gen_selector_tables.c --full. Do not edit. */
#ifndef SELFULL_H
#define SELFULL_H
#include <stdint.h>
#define SELFULL_NSTEP 3103
#define SELFULL_NBANK 5
#define SELFULL_NPAGE 14
#define SELFULL_BANK0 2
#define SELFULL_MAPBANK 7
#define SELFULL_STEPBANK 8
extern const uint8_t gg_selfull_steps[];
extern const uint8_t gg_selfull_rec0[];
extern const uint8_t gg_selfull_rec1[];
extern const uint8_t gg_selfull_rec2[];
extern const uint8_t gg_selfull_rec3[];
extern const uint8_t gg_selfull_rec4[];
extern const uint8_t gg_selfull_map[];
extern const uint8_t gg_selfull_hi[];
extern const uint8_t gg_sel_bstream[];
extern const uint8_t gg_sel_bptr[];
extern const uint8_t gg_sel_bpre[];
#endif
