#!/usr/bin/env python3
"""Deterministic input traces for the frame timeline.

Three workloads, because one average number hides the thing that actually
matters. Normal motion says what a frame usually costs; the adversarial trace
says what the spikes cost; the stress trace says where the architecture stops
coping. They are scripted rather than recorded so every build under comparison
sees byte-identical input.
"""
import sys
from pathlib import Path

UP, DOWN, LEFT, RIGHT, SL, SR = 1, 2, 4, 8, 0x20, 0x40   # see tilesector_polar.h; 0x10 is SPEED and is deliberately never set

def hold(v, n):      return [v] * n
def alternate(a, b, n, period): return [a if (i // period) % 2 == 0 else b for i in range(n)]

TRACES = {
    # Walking forward with gentle course corrections: the common case.
    "cruise": hold(UP, 40) + hold(UP | LEFT, 8) + hold(UP, 40) + hold(UP | RIGHT, 8) +
              hold(UP, 40) + hold(0, 4) + hold(UP, 40),
    # Spinning on the spot and reversing direction. Every frame changes the whole
    # visible set, so nothing upstream can be reused and span counts peak.
    "spin": alternate(LEFT, LEFT, 60, 60) + alternate(RIGHT, RIGHT, 60, 60) +
            alternate(LEFT, RIGHT, 60, 4),
    # Approaching and rounding corners while strafing: thin spans, many of them,
    # and rapid changes in which keys the recipe grid selects.
    "corners": hold(UP, 20) + hold(UP | SL, 12) + hold(LEFT, 10) + hold(UP, 16) +
               hold(UP | SR, 12) + hold(RIGHT, 10) + hold(UP, 16) +
               hold(SL, 14) + hold(UP | LEFT, 18) + hold(SR, 14) + hold(UP | RIGHT, 18),
    # Not representative play: everything at once, to find the ceiling.
    # Projection-oracle sweeps: isolate one camera degree of freedom at a time.
    # The return leg is intentional: hysteresis / retained-state errors then show
    # up as a different answer at the same geometric pose.
    "proj_rotate": hold(RIGHT, 48) + hold(LEFT, 96) + hold(RIGHT, 48),
    "proj_depth":  hold(DOWN, 40) + hold(UP, 80) + hold(DOWN, 40),
    "proj_strafe": hold(SL, 40) + hold(SR, 80) + hold(SL, 40),
    "stress": alternate(UP | LEFT, UP | RIGHT, 120, 3) +
              alternate(UP | SL | LEFT, UP | SR | RIGHT, 120, 2),
}

name = sys.argv[1]
out = Path(sys.argv[2])
t = TRACES[name]
L = ["/* GENERATED by tools/frame/gen_traces.py. Do not edit. */",
     "#include <stdint.h>",
     f"/* trace: {name}, {len(t)} frames */",
     f"const uint16_t k_tsp_trace_len = {len(t)};",
     f"const uint8_t k_tsp_trace[{len(t)}] = {{"]
for i in range(0, len(t), 20):
    L.append("  " + ",".join(str(x) for x in t[i:i+20]) + ",")
L.append("};")
out.write_text("\n".join(L) + "\n")
print(f"{name}: {len(t)} frames -> {out}")
